### ISSUE TITLE
Essentia ImportError: cannot import name _essentia on WSL Kali Linux image

### ISSUE THREAD

**Issue by skrowten-hermit** [MTG/essentia#1024]
I am trying to learn how to use the Essentia (with Gaia) library for audio/speech anyalysis. I started by installing on my WSL Kali Linux image.

Firstly, I installed `gaia` as mentioned [here ](https://github.com/MTG/gaia). Then, I have followed the installation instructions as described [here](https://essentia.upf.edu/installing.html) to install `essentia`. The installation was successful. And the libraries got installed in:

    skrowten-hermit@W10PC:~/essentia-work/essentia$ ls /usr/local/lib/
    libessentia.so  libgaia2.a  pkgconfig  python2.7  python3  python3.8

I went a step ahead and installed essentia using pip as `sudo pip install essentia`. That was successful as well and is installed well with the files present as expected:

    skrowten-hermit@HOLY-DIVER-W10PC:~/essentia-work/essentia$ ls /usr/local/lib/python2.7/dist-packages/essentia/
    algorithms.py           essentia_extractor.py   __init__.py             pool.py                 pytools/                streaming.pyc           utils.pyc
    algorithms.pyc          essentia_extractor.pyc  __init__.pyc            pool.pyc                standard.py             translate.py            weka/
    common.py               _essentia.so            plotting.py             progress.py             standard.pyc            translate.pyc
    common.pyc              extractor/              plotting.pyc            progress.pyc            streaming.py            utils.py

Then I decided to test it as mentioned [here](https://essentia.upf.edu/FAQ.html#running-tests). 

    skrowten-hermit@W10PC:~/essentia-work/essentia$ ./waf run_python_tests
    Running python unit tests using /usr/bin/python
    cp: cannot stat 'build/src/python/_essentia*.so': No such file or directory
    Traceback (most recent call last):
      File "test/src/unittests/all_tests.py", line 27, in <module>
        import essentia
      File "/home/skrowten-hermit/essentia-work/essentia/build/python/essentia/__init__.py", line 1, in <module>
        from . import _essentia
    ImportError: cannot import name _essentia
    failed to run python tests. Check test output

Even when I try importing it from python prompt, I get the error:

    Python 2.7.18 (default, Apr 20 2020, 20:30:41)
    [GCC 9.3.0] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import essentia
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/local/lib/python3/dist-packages/essentia/__init__.py", line 1, in <module>
        from . import _essentia
    ImportError: cannot import name _essentia
    >>> import sys
    >>> sys.path
    ['', '/usr/local/lib/python3/dist-packages', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/home/skrowten-hermit/.local/lib/python2.7/site-packages', '/usr/lib/python2.7/dist-packages']

As it can be seen my PYTHONPATH has been updated to look for the library where it's installed too.

I have read the issues #979 (even though it's on MacOS, it's still open and no response yet), #436 (I even tried solutions there) but no avail. It would be great if someone helps me gets the above error sorted. I'm sure it's some minor tweak that needs to be done to sort this out. Can someone please help?

Also, since basic (python) tests fail, I would like to know if C++ code would be affected in any way?

**Comment by dbogdanov** [comment]
This could be something with a proper `_essentia.so` naming for your platform.  Btw, Python2 is outdated, and won't be supported anymore. Can you see the same problem for Python 3?
