### ISSUE TITLE
Can't install via pip any more

### ISSUE THREAD

**Issue by A-V-lab** [MTG/essentia#1091]
pip installation of essentia fails (version 20.2.2 with python 3.9 on manjaro). I am running out of ideas. Can anyone help me?

Here is what I think is the relevant section from the log:

```
2021-01-03T19:22:40,213     ================================ CONFIGURATION SUMMARY ================================
2021-01-03T19:22:40,213     - using FFTW for FFT

2021-01-03T19:22:40,213     - fftw detected!
2021-01-03T19:22:40,213     - FFmpeg / libav detected!
2021-01-03T19:22:40,213     - libsamplerate (SRC) detected!
2021-01-03T19:22:40,213       The following algorithms will be included: ['MonoWriter', 'Resample', 'EqloudLoader', 'AudioLoader', 'EasyLoader', 'AudioWriter', 'MonoLoader']

2021-01-03T19:22:40,213     - TagLib detected!
2021-01-03T19:22:40,213       The following algorithms will be included: ['MetadataReader', 'MusicExtractor', 'FreesoundExtractor']

2021-01-03T19:22:40,213     - libyaml detected!
2021-01-03T19:22:40,213       The following algorithms will be included: ['YamlInput', 'YamlOutput']

2021-01-03T19:22:40,213     - Essentia is configured without Gaia2.
2021-01-03T19:22:40,213       The following algorithms will be ignored: ['GaiaTransform', 'MusicExtractorSVM']
2021-01-03T19:22:40,213       Examples requiring Gaia2 will be ignored

2021-01-03T19:22:40,213     - Chromaprint detected!
2021-01-03T19:22:40,214       The following algorithms will be included: ['Chromaprinter']

2021-01-03T19:22:40,214     - Essentia is configured without Tensorflow.
2021-01-03T19:22:40,214       The following algorithms will be ignored: ['TensorflowPredict', 'TensorflowPredictMusiCNN', 'TensorflowPredictVGGish']
2021-01-03T19:22:40,214     Building all the algorithms
2021-01-03T19:22:40,214     Ignoring the following algorithms: FFTKComplex, IFFTK, FFTAComplex, TensorflowPredictMusiCNN, IFFTKComplex, FFTK, TensorflowPredict, GaiaTransform, IFFTAComplex, TensorflowPredictVGGish, FFTA, IFFTA, MusicExtractorSVM
2021-01-03T19:22:40,214     Created algorithms registration file

2021-01-03T19:22:40,214     ---------------------------------------------------------------------------------------
2021-01-03T19:22:40,214     - Building static library
2021-01-03T19:22:40,214     Static dependencies found in packaging/debian_3rdparty/lib/pkgconfig will be used for:
2021-01-03T19:22:40,214     - Building Python extension
2021-01-03T19:22:40,214     =======================================================================================
2021-01-03T19:22:40,214     'configure' finished successfully (0.796s)
2021-01-03T19:22:40,314     /tmp/pip-install-xnt22e8f/essentia/wscript:302: SyntaxWarning: "is not" with a literal. Did you mean "!="?
2021-01-03T19:22:40,314       if ctx.env.CXX_NAME is not "clang":
2021-01-03T19:22:40,356     Waf: Entering directory `/tmp/pip-install-xnt22e8f/essentia/build'
2021-01-03T19:22:40,562     → building from /tmp/pip-install-xnt22e8f/essentia
2021-01-03T19:22:40,562     → building from /tmp/pip-install-xnt22e8f/essentia/src
2021-01-03T19:22:40,562     Building all the algorithms
2021-01-03T19:22:40,562     Ignoring the following algorithms: IFFTAComplex, FFTK, IFFTK, GaiaTransform, TensorflowPredictVGGish, FFTAComplex, TensorflowPredict, TensorflowPredictMusiCNN, FFTKComplex, IFFTA, IFFTKComplex, MusicExtractorSVM, FFTA
2021-01-03T19:22:40,562     Created algorithms registration file
2021-01-03T19:22:40,562     → building from /tmp/pip-install-xnt22e8f/essentia/src/python
2021-01-03T19:22:40,562     Waf: Leaving directory `/tmp/pip-install-xnt22e8f/essentia/build'
2021-01-03T19:22:40,562     source not found: '../essentia.pc.in' in bld(source='../essentia.pc.in', target='', meths=['process_rule', 'process_source'], features=[], path=/tmp/pip-install-xnt22e8f/essentia/src, idx=2, tg_idx_count=2, PREFIX='/tmp/pip-install-xnt22e8f/essentia/tmp', VERSION='2.1-beta6-dev', REQUIRESPRIVATE='fftw3f eigen3 libavformat libavcodec libavutil libavresample samplerate taglib yaml-0.1 libchromaprint', LFLAGS='-lfftw3f -lm -lavformat -lavcodec -lva -lmp3lame -lavutil -lavutil -lm -lavcodec -lva -lmp3lame -lavutil -lm -lavutil -lm -lavresample -lavutil -lm -lsamplerate -ltag -lz -lyaml -lchromaprint -lfftw3f', LPATHS='-L/tmp/pip-install-xnt22e8f/essentia/packaging/debian_3rdparty/lib', _name='', posted=True) in /tmp/pip-install-xnt22e8f/essentia/src
2021-01-03T19:22:40,682     /tmp/pip-install-xnt22e8f/essentia/wscript:302: SyntaxWarning: "is not" with a literal. Did you mean "!="?
2021-01-03T19:22:40,682       if ctx.env.CXX_NAME is not "clang":
2021-01-03T19:22:40,727     Waf: Entering directory `/tmp/pip-install-xnt22e8f/essentia/build'
2021-01-03T19:22:40,944     → building from /tmp/pip-install-xnt22e8f/essentia
2021-01-03T19:22:40,944     → building from /tmp/pip-install-xnt22e8f/essentia/src
2021-01-03T19:22:40,944     Building all the algorithms
2021-01-03T19:22:40,944     Ignoring the following algorithms: FFTKComplex, IFFTKComplex, GaiaTransform, IFFTA, IFFTAComplex, MusicExtractorSVM, TensorflowPredict, TensorflowPredictMusiCNN, FFTA, FFTK, FFTAComplex, TensorflowPredictVGGish, IFFTK
2021-01-03T19:22:40,945     Created algorithms registration file
2021-01-03T19:22:40,945     → building from /tmp/pip-install-xnt22e8f/essentia/src/python
2021-01-03T19:22:40,945     Waf: Leaving directory `/tmp/pip-install-xnt22e8f/essentia/build'
2021-01-03T19:22:40,945     source not found: '../essentia.pc.in' in bld(source='../essentia.pc.in', target='', meths=['process_rule', 'process_source'], features=[], path=/tmp/pip-install-xnt22e8f/essentia/src, idx=2, tg_idx_count=2, PREFIX='/tmp/pip-install-xnt22e8f/essentia/tmp', VERSION='2.1-beta6-dev', REQUIRESPRIVATE='fftw3f eigen3 libavformat libavcodec libavutil libavresample samplerate taglib yaml-0.1 libchromaprint', LFLAGS='-lfftw3f -lm -lavformat -lavcodec -lva -lmp3lame -lavutil -lavutil -lm -lavcodec -lva -lmp3lame -lavutil -lm -lavutil -lm -lavresample -lavutil -lm -lsamplerate -ltag -lz -lyaml -lchromaprint -lfftw3f', LPATHS='-L/tmp/pip-install-xnt22e8f/essentia/packaging/debian_3rdparty/lib', _name='', posted=True) in /tmp/pip-install-xnt22e8f/essentia/src
2021-01-03T19:22:40,975     Traceback (most recent call last):
2021-01-03T19:22:40,976       File "<string>", line 1, in <module>
2021-01-03T19:22:40,976       File "/tmp/pip-install-xnt22e8f/essentia/setup.py", line 123, in <module>
2021-01-03T19:22:40,976         setup(
2021-01-03T19:22:40,976       File "/usr/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
2021-01-03T19:22:40,976         return distutils.core.setup(**attrs)
2021-01-03T19:22:40,976       File "/usr/lib/python3.9/distutils/core.py", line 148, in setup
2021-01-03T19:22:40,976         dist.run_commands()
2021-01-03T19:22:40,976       File "/usr/lib/python3.9/distutils/dist.py", line 966, in run_commands
2021-01-03T19:22:40,976         self.run_command(cmd)
2021-01-03T19:22:40,976       File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
2021-01-03T19:22:40,976         cmd_obj.run()
2021-01-03T19:22:40,976       File "/usr/lib/python3.9/site-packages/setuptools/command/install.py", line 61, in run
2021-01-03T19:22:40,976         return orig.install.run(self)
2021-01-03T19:22:40,976       File "/usr/lib/python3.9/distutils/command/install.py", line 546, in run
2021-01-03T19:22:40,976         self.run_command('build')
2021-01-03T19:22:40,977       File "/usr/lib/python3.9/distutils/cmd.py", line 313, in run_command
2021-01-03T19:22:40,977         self.distribution.run_command(command)
2021-01-03T19:22:40,977       File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
2021-01-03T19:22:40,977         cmd_obj.run()
2021-01-03T19:22:40,977       File "/usr/lib/python3.9/distutils/command/build.py", line 135, in run
2021-01-03T19:22:40,977         self.run_command(cmd_name)
2021-01-03T19:22:40,977       File "/usr/lib/python3.9/distutils/cmd.py", line 313, in run_command
2021-01-03T19:22:40,977         self.distribution.run_command(command)
2021-01-03T19:22:40,977       File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
2021-01-03T19:22:40,977         cmd_obj.run()
2021-01-03T19:22:40,977       File "/tmp/pip-install-xnt22e8f/essentia/setup.py", line 54, in run
2021-01-03T19:22:40,977         library = glob.glob('tmp/lib/python*/*-packages/essentia')[0]
2021-01-03T19:22:40,977     IndexError: list index out of range
2021-01-03T19:22:40,993 ERROR: Command errored out with exit status 1: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-xnt22e8f/essentia/setup.py'"'"'; __file__='"'"'/tmp/pip-install-xnt22e8f/essentia/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-5yzh7x_3/install-record.txt --single-version-externally-managed --compile --install-headers /usr/include/python3.9/essentia Check the logs for full command output.
```
Edit: I fixed a previous error where ffmpeg was not detected but it didn't change the outcome; the installation still fails.
[essentia.log](https://github.com/MTG/essentia/files/5762050/essentia.log)
Edit 2: Uploaded the full log as an attachment.

**Comment by A-V-lab** [comment]
I just realized that it says ffmpeg is missing, which is strange because I have it installed. Perhaps that is the reason why it fails? I will investigate this for now. If you have other suggestions please let me know.

**Comment by A-V-lab** [comment]
I now resorted to compiling it via the AUR (+ installed libavresample also from AUR) and gave up on pip after trying for hours.

**Comment by dbogdanov** [comment]
New wheels, including Python 3.9, are available on PyPI now.

**Comment by dbogdanov** [comment]
@Ogala What system (OS, CPU) are you installing on? (Is it a MacOS, Apple silicon?)

Installing from pip should pick up the prebuilt binaries from PyPI for your architecture, otherwise the build script is launched which what happened according to your log.

**Comment by Ogala** [comment]
@dbogdanov yes, this is docker on Apple M2.

**Comment by guilhemchalancon** [comment]
@Ogala have you found any resolution for this?

**Comment by anomitro-ZenMusic** [comment]
Here with the same problem.

**Comment by anomitro-ZenMusic** [comment]
Not sure if this is the right way, but I am attempting to build it from the source
my image was missing a few dependencies( libeigen3-dev pkg-config), which I am guessing are build dependencies, and maybe since install it wwith pip on mac-m2 builds it from the source, the build dependencies were assumed to be there. 

Steps: 
apt-get install libeigen3-dev pkg-config

then clone the repo
cd essentia
python3 waf configure --build-static --with-python --with-examples --mode=release
python3 waf
python3 waf install


Another issue I faced was that essentia requires numpy=1.2.6
