### ISSUE TITLE
Error instantiating  Spectrum algorithm

### ISSUE THREAD

**Issue by vigneshishwar89** [MTG/essentia#114]
We are running some essentia code in matlab and it crashes while using fftw. This is a stack trace of the error.

```
#1  0xab5b5fd0 in fftwf_kernel_free (p=0x0) at /mathworks/BLR/devel/bat/A3p0/build/3p/sources/fftw/kernel/kalloc.c:68
#2  0xab6947cd in fftwf_free (p=0x0) at /mathworks/BLR/devel/bat/A3p0/build/3p/sources/fftw/api/malloc.c:31
#3  0xab92a838 in essentia::standard::FFTW::createFFTObject (this=this@entry=0xafc0a458, size=1024)
    at ../src/algorithms/standard/fftw.cpp:96
#4  0xab92ad09 in essentia::standard::FFTW::configure (this=0xafc0a458) at ../src/algorithms/standard/fftw.cpp:82
#5  0xab73394f in essentia::EssentiaFactory<essentia::standard::Algorithm>::create_i (this=0xaf93afc8, id=...)
    at /usr/local/include/essentia/algorithmfactory_impl.h:78
#6  0xab778127 in create (id=...) at /home/vignesh/essentia/src/essentia/algorithmfactory.h:86
#7  essentia::standard::Spectrum::Spectrum (this=0xafc0a248) at /home/vignesh/essentia/src/algorithms/standard/spectrum.h:44
#8  0xab778270 in essentia::EssentiaFactory<essentia::standard::Algorithm>::Registrar<essentia::standard::Spectrum, essentia::standard::Spectrum>::create () at /home/vignesh/essentia/src/essentia/algorithmfactory.h:138
#9  0xab7337fb in essentia::EssentiaFactory<essentia::standard::Algorithm>::create_i (this=0xaf93afc8, id=...)
    at /usr/local/include/essentia/algorithmfactory_impl.h:59
#10 0xab732ff4 in essentia::EssentiaFactory<essentia::standard::Algorithm>::create (id=...)
    at /usr/local/include/essentia/algorithmfactory.h:86
```

It looks like spectrum creates an fft algorithm which calls `fftwf_free` on `_input` during configure which may not be instantiated yet. 

This doesn't seem to happen on 64 bit machine but we are not sure if its because we are using system fftw instead of matlab fftw or if its something else.

**Comment by alastair** [comment]
closing because we've not had to address this since it was raised.
