### ISSUE TITLE
pip install essentia fails on windows 10

### ISSUE THREAD

**Issue by Arjannikov** [MTG/essentia#1157]
(base) PS C:\Windows\system32> pip install essentia
Collecting essentia
  Using cached essentia-2.1b6.dev234.tar.gz (1.1 MB)
Requirement already satisfied: numpy>=1.8.2 in c:\programdata\anaconda3\lib\site-packages (from essentia) (1.17.4)
Requirement already satisfied: six in c:\programdata\anaconda3\lib\site-packages (from essentia) (1.13.0)
Requirement already satisfied: pyyaml in c:\programdata\anaconda3\lib\site-packages (from essentia) (5.3.1)
Building wheels for collected packages: essentia
  Building wheel for essentia (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\ProgramData\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Tom\\AppData\\Local\\Temp\\pip-install-qi5yvn4b\\essentia\\setup.py'"'"'; __file__='"'"'C:\\Users\\Tom\\AppData\\Local\\Temp\\pip-install-qi5yvn4b\\essentia\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\Tom\AppData\Local\Temp\pip-wheel-zp3vtmh1'
       cwd: C:\Users\Tom\AppData\Local\Temp\pip-install-qi5yvn4b\essentia\
  Complete output (87 lines):
  Error parsing the number of dev commits: %s
  C:\ProgramData\Anaconda3\lib\site-packages\setuptools\dist.py:452: UserWarning: Normalizing '2.1-beta6-dev0' to '2.1b6.dev0'
    warnings.warn(tmpl.format(**locals()))
  running bdist_wheel
  running build
  running build_ext
  'rm' is not recognized as an internal or external command,
  operable program or batch file.
  '.' is not recognized as an internal or external command,
  operable program or batch file.
  Setting top to                           : C:\Users\Tom\AppData\Local\Temp\pip-install-qi5yvn4b\essentia
  Setting out to                           : C:\Users\Tom\AppData\Local\Temp\pip-install-qi5yvn4b\essentia\build
  Traceback (most recent call last):
    File "C:\Users\Tom\AppData\Local\Temp\pip-install-qi5yvn4b\essentia\waf3-2.0.18-77b2fa32f72970f15a949a4a564841e2\waflib\Scripting.py", line 119, in waf_entry_point
      run_commands()
    File "C:\Users\Tom\AppData\Local\Temp\pip-install-qi5yvn4b\essentia\waf3-2.0.18-77b2fa32f72970f15a949a4a564841e2\waflib\Scripting.py", line 182, in run_commands
      ctx=run_command(cmd_name)
    File "C:\Users\Tom\AppData\Local\Temp\pip-install-qi5yvn4b\essentia\waf3-2.0.18-77b2fa32f72970f15a949a4a564841e2\waflib\Scripting.py", line 173, in run_command
      ctx.execute()
    File "C:\Users\Tom\AppData\Local\Temp\pip-install-qi5yvn4b\essentia\waf3-2.0.18-77b2fa32f72970f15a949a4a564841e2\waflib\Configure.py", line 85, in execute
      super(ConfigurationContext,self).execute()
    File "C:\Users\Tom\AppData\Local\Temp\pip-install-qi5yvn4b\essentia\waf3-2.0.18-77b2fa32f72970f15a949a4a564841e2\waflib\Context.py", line 85, in execute
      self.recurse([os.path.dirname(g_module.root_path)])
    File "C:\Users\Tom\AppData\Local\Temp\pip-install-qi5yvn4b\essentia\waf3-2.0.18-77b2fa32f72970f15a949a4a564841e2\waflib\Context.py", line 126, in recurse
      user_function(self)
  Traceback (most recent call last):
    File "C:\Users\Tom\AppData\Local\Temp\pip-install-qi5yvn4b\essentia\waf3-2.0.18-77b2fa32f72970f15a949a4a564841e2\waflib\Scripting.py", line 119, in waf_entry_point
      run_commands()
    File "C:\Users\Tom\AppData\Local\Temp\pip-install-qi5yvn4b\essentia\waf3-2.0.18-77b2fa32f72970f15a949a4a564841e2\waflib\Scripting.py", line 182, in run_commands
      ctx=run_command(cmd_name)
    File "C:\Users\Tom\AppData\Local\Temp\pip-install-qi5yvn4b\essentia\waf3-2.0.18-77b2fa32f72970f15a949a4a564841e2\waflib\Scripting.py", line 173, in run_command
      ctx.execute()
    File "C:\Users\Tom\AppData\Local\Temp\pip-install-qi5yvn4b\essentia\waf3-2.0.18-77b2fa32f72970f15a949a4a564841e2\waflib\Configure.py", line 85, in execute
      super(ConfigurationContext,self).execute()
    File "C:\Users\Tom\AppData\Local\Temp\pip-install-qi5yvn4b\essentia\waf3-2.0.18-77b2fa32f72970f15a949a4a564841e2\waflib\Context.py", line 85, in execute
      self.recurse([os.path.dirname(g_module.root_path)])
    File "C:\Users\Tom\AppData\Local\Temp\pip-install-qi5yvn4b\essentia\waf3-2.0.18-77b2fa32f72970f15a949a4a564841e2\waflib\Context.py", line 126, in recurse
      user_function(self)
    File "C:\Users\Tom\AppData\Local\Temp\pip-install-qi5yvn4b\essentia\wscript", line 83, in configure
      print('\u2192 configuring the project in ' + ctx.path.abspath())
    File "C:\ProgramData\Anaconda3\lib\encodings\cp1252.py", line 19, in encode
      return codecs.charmap_encode(input,self.errors,encoding_table)[0]
  UnicodeEncodeError: 'charmap' codec can't encode character '\u2192' in position 0: character maps to <undefined>

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "waf", line 168, in <module>
      Scripting.waf_entry_point(cwd, VERSION, wafdir)
    File "C:\Users\Tom\AppData\Local\Temp\pip-install-qi5yvn4b\essentia\waf3-2.0.18-77b2fa32f72970f15a949a4a564841e2\waflib\Scripting.py", line 136, in waf_entry_point
      traceback.print_exc(file=sys.stdout)
    File "C:\ProgramData\Anaconda3\lib\traceback.py", line 163, in print_exc
      print_exception(*sys.exc_info(), limit=limit, file=file, chain=chain)
    File "C:\ProgramData\Anaconda3\lib\traceback.py", line 105, in print_exception
      print(line, file=file, end="")
    File "C:\ProgramData\Anaconda3\lib\encodings\cp1252.py", line 19, in encode
      return codecs.charmap_encode(input,self.errors,encoding_table)[0]
  UnicodeEncodeError: 'charmap' codec can't encode character '\u2192' in position 114: character maps to <undefined>
  The project was not configured: run "waf configure" first!
  The project was not configured: run "waf configure" first!
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\Tom\AppData\Local\Temp\pip-install-qi5yvn4b\essentia\setup.py", line 144, in <module>
      'install_lib': EssentiaInstall
    File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "C:\ProgramData\Anaconda3\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\ProgramData\Anaconda3\lib\site-packages\wheel\bdist_wheel.py", line 290, in run
      self.run_command('build')
    File "C:\ProgramData\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\ProgramData\Anaconda3\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "C:\ProgramData\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\Tom\AppData\Local\Temp\pip-install-qi5yvn4b\essentia\setup.py", line 54, in run
      library = glob.glob('tmp/lib/python*/*-packages/essentia')[0]
  IndexError: list index out of range
  ----------------------------------------
  ERROR: Failed building wheel for essentia
  Running setup.py clean for essentia
Failed to build essentia
Installing collected packages: essentia
    Running setup.py install for essentia ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\ProgramData\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Tom\\AppData\\Local\\Temp\\pip-install-qi5yvn4b\\essentia\\setup.py'"'"'; __file__='"'"'C:\\Users\\Tom\\AppData\\Local\\Temp\\pip-install-qi5yvn4b\\essentia\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Tom\AppData\Local\Temp\pip-record-2gz6bxfq\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\ProgramData\Anaconda3\Include\essentia'
         cwd: C:\Users\Tom\AppData\Local\Temp\pip-install-qi5yvn4b\essentia\
    Complete output (89 lines):
    Error parsing the number of dev commits: %s
    C:\ProgramData\Anaconda3\lib\site-packages\setuptools\dist.py:452: UserWarning: Normalizing '2.1-beta6-dev0' to '2.1b6.dev0'
      warnings.warn(tmpl.format(**locals()))
    running install
    running build
    running build_ext
    'rm' is not recognized as an internal or external command,
    operable program or batch file.
    '.' is not recognized as an internal or external command,
    operable program or batch file.
    Setting top to                           : C:\Users\Tom\AppData\Local\Temp\pip-install-qi5yvn4b\essentia
    Setting out to                           : C:\Users\Tom\AppData\Local\Temp\pip-install-qi5yvn4b\essentia\build
    Traceback (most recent call last):
      File "C:\Users\Tom\AppData\Local\Temp\pip-install-qi5yvn4b\essentia\waf3-2.0.18-77b2fa32f72970f15a949a4a564841e2\waflib\Scripting.py", line 119, in waf_entry_point
        run_commands()
      File "C:\Users\Tom\AppData\Local\Temp\pip-install-qi5yvn4b\essentia\waf3-2.0.18-77b2fa32f72970f15a949a4a564841e2\waflib\Scripting.py", line 182, in run_commands
        ctx=run_command(cmd_name)
      File "C:\Users\Tom\AppData\Local\Temp\pip-install-qi5yvn4b\essentia\waf3-2.0.18-77b2fa32f72970f15a949a4a564841e2\waflib\Scripting.py", line 173, in run_command
        ctx.execute()
      File "C:\Users\Tom\AppData\Local\Temp\pip-install-qi5yvn4b\essentia\waf3-2.0.18-77b2fa32f72970f15a949a4a564841e2\waflib\Configure.py", line 85, in execute
        super(ConfigurationContext,self).execute()
      File "C:\Users\Tom\AppData\Local\Temp\pip-install-qi5yvn4b\essentia\waf3-2.0.18-77b2fa32f72970f15a949a4a564841e2\waflib\Context.py", line 85, in execute
        self.recurse([os.path.dirname(g_module.root_path)])
      File "C:\Users\Tom\AppData\Local\Temp\pip-install-qi5yvn4b\essentia\waf3-2.0.18-77b2fa32f72970f15a949a4a564841e2\waflib\Context.py", line 126, in recurse
        user_function(self)
    Traceback (most recent call last):
      File "C:\Users\Tom\AppData\Local\Temp\pip-install-qi5yvn4b\essentia\waf3-2.0.18-77b2fa32f72970f15a949a4a564841e2\waflib\Scripting.py", line 119, in waf_entry_point
        run_commands()
      File "C:\Users\Tom\AppData\Local\Temp\pip-install-qi5yvn4b\essentia\waf3-2.0.18-77b2fa32f72970f15a949a4a564841e2\waflib\Scripting.py", line 182, in run_commands
        ctx=run_command(cmd_name)
      File "C:\Users\Tom\AppData\Local\Temp\pip-install-qi5yvn4b\essentia\waf3-2.0.18-77b2fa32f72970f15a949a4a564841e2\waflib\Scripting.py", line 173, in run_command
        ctx.execute()
      File "C:\Users\Tom\AppData\Local\Temp\pip-install-qi5yvn4b\essentia\waf3-2.0.18-77b2fa32f72970f15a949a4a564841e2\waflib\Configure.py", line 85, in execute
        super(ConfigurationContext,self).execute()
      File "C:\Users\Tom\AppData\Local\Temp\pip-install-qi5yvn4b\essentia\waf3-2.0.18-77b2fa32f72970f15a949a4a564841e2\waflib\Context.py", line 85, in execute
        self.recurse([os.path.dirname(g_module.root_path)])
      File "C:\Users\Tom\AppData\Local\Temp\pip-install-qi5yvn4b\essentia\waf3-2.0.18-77b2fa32f72970f15a949a4a564841e2\waflib\Context.py", line 126, in recurse
        user_function(self)
      File "C:\Users\Tom\AppData\Local\Temp\pip-install-qi5yvn4b\essentia\wscript", line 83, in configure
        print('\u2192 configuring the project in ' + ctx.path.abspath())
      File "C:\ProgramData\Anaconda3\lib\encodings\cp1252.py", line 19, in encode
        return codecs.charmap_encode(input,self.errors,encoding_table)[0]
    UnicodeEncodeError: 'charmap' codec can't encode character '\u2192' in position 0: character maps to <undefined>

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "waf", line 168, in <module>
        Scripting.waf_entry_point(cwd, VERSION, wafdir)
      File "C:\Users\Tom\AppData\Local\Temp\pip-install-qi5yvn4b\essentia\waf3-2.0.18-77b2fa32f72970f15a949a4a564841e2\waflib\Scripting.py", line 136, in waf_entry_point
        traceback.print_exc(file=sys.stdout)
      File "C:\ProgramData\Anaconda3\lib\traceback.py", line 163, in print_exc
        print_exception(*sys.exc_info(), limit=limit, file=file, chain=chain)
      File "C:\ProgramData\Anaconda3\lib\traceback.py", line 105, in print_exception
        print(line, file=file, end="")
      File "C:\ProgramData\Anaconda3\lib\encodings\cp1252.py", line 19, in encode
        return codecs.charmap_encode(input,self.errors,encoding_table)[0]
    UnicodeEncodeError: 'charmap' codec can't encode character '\u2192' in position 114: character maps to <undefined>
    The project was not configured: run "waf configure" first!
    The project was not configured: run "waf configure" first!
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Tom\AppData\Local\Temp\pip-install-qi5yvn4b\essentia\setup.py", line 144, in <module>
        'install_lib': EssentiaInstall
      File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "C:\ProgramData\Anaconda3\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "C:\ProgramData\Anaconda3\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "C:\ProgramData\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\ProgramData\Anaconda3\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "C:\ProgramData\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\Tom\AppData\Local\Temp\pip-install-qi5yvn4b\essentia\setup.py", line 54, in run
        library = glob.glob('tmp/lib/python*/*-packages/essentia')[0]
    IndexError: list index out of range
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\ProgramData\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Tom\\AppData\\Local\\Temp\\pip-install-qi5yvn4b\\essentia\\setup.py'"'"'; __file__='"'"'C:\\Users\\Tom\\AppData\\Local\\Temp\\pip-install-qi5yvn4b\\essentia\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Tom\AppData\Local\Temp\pip-record-2gz6bxfq\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\ProgramData\Anaconda3\Include\essentia' Check the logs for full command output.

**Comment by Arjannikov** [comment]
One thing to note, near the top, there are some unrecognized commands, specifically 'rm', which is not available in Windows 10.
Another thing to note, there is a Unicode error for character '\u2192'.
And finally, there's the IndexError.

Please help :)

**Comment by dbogdanov** [comment]
Hi @Arjannikov ! 
You can run `pip install essentia` inside a [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/about) (WSL). We do not provide pip wheels for Windows yet.
