### ISSUE TITLE
Unable to compile on Essentia on OSX 10.14.6

### ISSUE THREAD

**Issue by sandybeachsystems** [MTG/essentia#1190]
When running the way script I get the following error:
Mac-mini:src gordon$ ../waf configure --build-static --with-python --with-examples --with-vamp
Setting top to                           : /Users/gordon/essentia/src 
Setting out to                           : /Users/gordon/essentia/src/build 

=======================Lightweight Mode : Ignoring ALL libraries except [''] =======================

Traceback (most recent call last):
  File "/Users/gordon/essentia/.waf-2.0.22-1241519b19b496207abef1f72bbf61c2/waflib/Scripting.py", line 119, in waf_entry_point
    run_commands()
  File "/Users/gordon/essentia/.waf-2.0.22-1241519b19b496207abef1f72bbf61c2/waflib/Scripting.py", line 182, in run_commands
    ctx=run_command(cmd_name)
  File "/Users/gordon/essentia/.waf-2.0.22-1241519b19b496207abef1f72bbf61c2/waflib/Scripting.py", line 173, in run_command
    ctx.execute()
  File "/Users/gordon/essentia/.waf-2.0.22-1241519b19b496207abef1f72bbf61c2/waflib/Configure.py", line 85, in execute
    super(ConfigurationContext,self).execute()
  File "/Users/gordon/essentia/.waf-2.0.22-1241519b19b496207abef1f72bbf61c2/waflib/Context.py", line 92, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "/Users/gordon/essentia/.waf-2.0.22-1241519b19b496207abef1f72bbf61c2/waflib/Context.py", line 133, in recurse
    user_function(self)
  File "/Users/gordon/essentia/src/wscript", line 146, in configure
    ctx.check_cfg(package=lib_map['EIGEN3'], uselib_store='EIGEN3',
AttributeError: 'ConfigurationContext' object has no attribute 'check_cfg'

**Comment by andresbrocco** [comment]
You should install essentia via homebrew: check out [this issue](https://github.com/MTG/homebrew-essentia/issues/32).

Then, you should point your pythonpath to the installation folder, (in my case `opt/homebrew/lib/python3.9/site-packages/essentia`). Follow [this tutorial](https://k0nze.dev/posts/python-relative-imports-vscode/), which advises you to create the `.vscode/settings.json` and `launch.json` files.

**Comment by meat-rock-research-group** [comment]
thanks, andre.
i managed to make it work, although not in openframeworks. i used docker.

enjoy your weekend.
best,ireti

    On Friday, September 8, 2023 at 09:50:23 PM GMT+1, André Sbrocco Figueiredo ***@***.***> wrote:  
 
 


You should install essentia via homebrew: check out this issue.

Then, you should point your pythonpath to the installation folder, (in my case opt/homebrew/lib/python3.9/site-packages/essentia). Follow this tutorial, which advises you to create the .vscode/settings.json and launch.json files.
