### ISSUE TITLE
pip install essentia issue

### ISSUE THREAD

**Issue by IshkMagar** [MTG/essentia#1202]
Using legacy 'setup.py install' for essentia, since package 'wheel' is not installed.
Installing collected packages: essentia
    Running setup.py install for essentia ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\tmaga\appdata\local\programs\python\python39\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\tmaga\\AppData\\Local\\Temp\\pip-install-318qz6l_\\essentia_676b3130b312482dbe5fc5ac5d14343b\\setup.py'"'"'; __file__='"'"'C:\\Users\\tmaga\\AppData\\Local\\Temp\\pip-install-318qz6l_\\essentia_676b3130b312482dbe5fc5ac5d14343b\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\tmaga\AppData\Local\Temp\pip-record-z_1xnyk8\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\tmaga\appdata\local\programs\python\python39\Include\essentia'
         cwd: C:\Users\tmaga\AppData\Local\Temp\pip-install-318qz6l_\essentia_676b3130b312482dbe5fc5ac5d14343b\
    Complete output (94 lines):
    c:\users\tmaga\appdata\local\programs\python\python39\lib\site-packages\setuptools\dist.py:484: UserWarning: Normalizing '2.1-beta5' to '2.1b5'
      warnings.warn(tmpl.format(**locals()))
    running install
    running build
    running build_ext
    'rm' is not recognized as an internal or external command,
    operable program or batch file.
    '.' is not recognized as an internal or external command,
    operable program or batch file.
    C:\Users\tmaga\AppData\Local\Temp\pip-install-318qz6l_\essentia_676b3130b312482dbe5fc5ac5d14343b\wscript:301: SyntaxWarning: "is not" with a literal. Did you mean "!="?
      if ctx.env.CXX_NAME is not "clang":
    Setting top to                           : C:\Users\tmaga\AppData\Local\Temp\pip-install-318qz6l_\essentia_676b3130b312482dbe5fc5ac5d14343b
    Setting out to                           : C:\Users\tmaga\AppData\Local\Temp\pip-install-318qz6l_\essentia_676b3130b312482dbe5fc5ac5d14343b\build
    Traceback (most recent call last):
      File "C:\Users\tmaga\AppData\Local\Temp\pip-install-318qz6l_\essentia_676b3130b312482dbe5fc5ac5d14343b\waf3-2.0.10-cf8ca5fa84387374f6d66295baab59ec\waflib\Scripting.py", line 119, in waf_entry_point
        run_commands()
      File "C:\Users\tmaga\AppData\Local\Temp\pip-install-318qz6l_\essentia_676b3130b312482dbe5fc5ac5d14343b\waf3-2.0.10-cf8ca5fa84387374f6d66295baab59ec\waflib\Scripting.py", line 179, in run_commands
        ctx=run_command(cmd_name)
      File "C:\Users\tmaga\AppData\Local\Temp\pip-install-318qz6l_\essentia_676b3130b312482dbe5fc5ac5d14343b\waf3-2.0.10-cf8ca5fa84387374f6d66295baab59ec\waflib\Scripting.py", line 170, in run_command
        ctx.execute()
      File "C:\Users\tmaga\AppData\Local\Temp\pip-install-318qz6l_\essentia_676b3130b312482dbe5fc5ac5d14343b\waf3-2.0.10-cf8ca5fa84387374f6d66295baab59ec\waflib\Configure.py", line 85, in execute
        super(ConfigurationContext,self).execute()
      File "C:\Users\tmaga\AppData\Local\Temp\pip-install-318qz6l_\essentia_676b3130b312482dbe5fc5ac5d14343b\waf3-2.0.10-cf8ca5fa84387374f6d66295baab59ec\waflib\Context.py", line 85, in execute
        self.recurse([os.path.dirname(g_module.root_path)])
      File "C:\Users\tmaga\AppData\Local\Temp\pip-install-318qz6l_\essentia_676b3130b312482dbe5fc5ac5d14343b\waf3-2.0.10-cf8ca5fa84387374f6d66295baab59ec\waflib\Context.py", line 126, in recurse
        user_function(self)
    Traceback (most recent call last):
      File "C:\Users\tmaga\AppData\Local\Temp\pip-install-318qz6l_\essentia_676b3130b312482dbe5fc5ac5d14343b\waf3-2.0.10-cf8ca5fa84387374f6d66295baab59ec\waflib\Scripting.py", line 119, in waf_entry_point
        run_commands()
      File "C:\Users\tmaga\AppData\Local\Temp\pip-install-318qz6l_\essentia_676b3130b312482dbe5fc5ac5d14343b\waf3-2.0.10-cf8ca5fa84387374f6d66295baab59ec\waflib\Scripting.py", line 179, in run_commands
        ctx=run_command(cmd_name)
      File "C:\Users\tmaga\AppData\Local\Temp\pip-install-318qz6l_\essentia_676b3130b312482dbe5fc5ac5d14343b\waf3-2.0.10-cf8ca5fa84387374f6d66295baab59ec\waflib\Scripting.py", line 170, in run_command
        ctx.execute()
      File "C:\Users\tmaga\AppData\Local\Temp\pip-install-318qz6l_\essentia_676b3130b312482dbe5fc5ac5d14343b\waf3-2.0.10-cf8ca5fa84387374f6d66295baab59ec\waflib\Configure.py", line 85, in execute
        super(ConfigurationContext,self).execute()
      File "C:\Users\tmaga\AppData\Local\Temp\pip-install-318qz6l_\essentia_676b3130b312482dbe5fc5ac5d14343b\waf3-2.0.10-cf8ca5fa84387374f6d66295baab59ec\waflib\Context.py", line 85, in execute
        self.recurse([os.path.dirname(g_module.root_path)])
      File "C:\Users\tmaga\AppData\Local\Temp\pip-install-318qz6l_\essentia_676b3130b312482dbe5fc5ac5d14343b\waf3-2.0.10-cf8ca5fa84387374f6d66295baab59ec\waflib\Context.py", line 126, in recurse
        user_function(self)
      File "C:\Users\tmaga\AppData\Local\Temp\pip-install-318qz6l_\essentia_676b3130b312482dbe5fc5ac5d14343b\wscript", line 83, in configure
        print('\u2192 configuring the project in ' + ctx.path.abspath())
      File "c:\users\tmaga\appdata\local\programs\python\python39\lib\encodings\cp1252.py", line 19, in encode
        return codecs.charmap_encode(input,self.errors,encoding_table)[0]
    UnicodeEncodeError: 'charmap' codec can't encode character '\u2192' in position 0: character maps to <undefined>

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\tmaga\AppData\Local\Temp\pip-install-318qz6l_\essentia_676b3130b312482dbe5fc5ac5d14343b\waf", line 165, in <module>
        Scripting.waf_entry_point(cwd, VERSION, wafdir)
      File "C:\Users\tmaga\AppData\Local\Temp\pip-install-318qz6l_\essentia_676b3130b312482dbe5fc5ac5d14343b\waf3-2.0.10-cf8ca5fa84387374f6d66295baab59ec\waflib\Scripting.py", line 136, in waf_entry_point
        traceback.print_exc(file=sys.stdout)
      File "c:\users\tmaga\appdata\local\programs\python\python39\lib\traceback.py", line 163, in print_exc
        print_exception(*sys.exc_info(), limit=limit, file=file, chain=chain)
      File "c:\users\tmaga\appdata\local\programs\python\python39\lib\traceback.py", line 105, in print_exception
        print(line, file=file, end="")
      File "c:\users\tmaga\appdata\local\programs\python\python39\lib\encodings\cp1252.py", line 19, in encode
        return codecs.charmap_encode(input,self.errors,encoding_table)[0]
    UnicodeEncodeError: 'charmap' codec can't encode character '\u2192' in position 149: character maps to <undefined>
    C:\Users\tmaga\AppData\Local\Temp\pip-install-318qz6l_\essentia_676b3130b312482dbe5fc5ac5d14343b\wscript:301: SyntaxWarning: "is not" with a literal. Did you mean "!="?
      if ctx.env.CXX_NAME is not "clang":
    The project was not configured: run "waf configure" first!
    C:\Users\tmaga\AppData\Local\Temp\pip-install-318qz6l_\essentia_676b3130b312482dbe5fc5ac5d14343b\wscript:301: SyntaxWarning: "is not" with a literal. Did you mean "!="?
      if ctx.env.CXX_NAME is not "clang":
    The project was not configured: run "waf configure" first!
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\tmaga\AppData\Local\Temp\pip-install-318qz6l_\essentia_676b3130b312482dbe5fc5ac5d14343b\setup.py", line 95, in <module>
        setup(
      File "c:\users\tmaga\appdata\local\programs\python\python39\lib\site-packages\setuptools\__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "c:\users\tmaga\appdata\local\programs\python\python39\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\tmaga\appdata\local\programs\python\python39\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "c:\users\tmaga\appdata\local\programs\python\python39\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\users\tmaga\appdata\local\programs\python\python39\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\users\tmaga\appdata\local\programs\python\python39\lib\distutils\command\install.py", line 546, in run
        self.run_command('build')
      File "c:\users\tmaga\appdata\local\programs\python\python39\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\tmaga\appdata\local\programs\python\python39\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\users\tmaga\appdata\local\programs\python\python39\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "c:\users\tmaga\appdata\local\programs\python\python39\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\tmaga\appdata\local\programs\python\python39\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\tmaga\AppData\Local\Temp\pip-install-318qz6l_\essentia_676b3130b312482dbe5fc5ac5d14343b\setup.py", line 46, in run
        library = glob.glob('tmp/lib/python*/*-packages/essentia')[0]
    IndexError: list index out of range
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\tmaga\appdata\local\programs\python\python39\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\tmaga\\AppData\\Local\\Temp\\pip-install-318qz6l_\\essentia_676b3130b312482dbe5fc5ac5d14343b\\setup.py'"'"'; __file__='"'"'C:\\Users\\tmaga\\AppData\\Local\\Temp\\pip-install-318qz6l_\\essentia_676b3130b312482dbe5fc5ac5d14343b\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\tmaga\AppData\Local\Temp\pip-record-z_1xnyk8\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\tmaga\appdata\local\programs\python\python39\Include\essentia' Check the logs for full command output.

**Comment by dbogdanov** [comment]
Wheels aren't yet supported for Windows (see  #1157).
