### ISSUE TITLE
Error in TonicIndianArtMusic function

### ISSUE THREAD

**Issue by sujoyrc** [MTG/essentia#1270]
Hi,
I am getting an error with the following code

```
import essentia.standard
src='AG_1a_Jaun.mp3'
loader = essentia.standard.MonoLoader(filename=src)
audio = loader()
tonic = essentia.standard.TonicIndianArtMusic(maxTonicFrequency=530)(audio)
```
I get the following error

```
>>> tonic = essentia.standard.TonicIndianArtMusic(maxTonicFrequency=530)(audio)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/antpc/anaconda3/lib/python3.8/site-packages/essentia/standard.py", line 44, in __init__
    self.configure(**kwargs)
  File "/home/antpc/anaconda3/lib/python3.8/site-packages/essentia/standard.py", line 64, in configure
    self.__configure__(**kwargs)
RuntimeError: Error while configuring TonicIndianArtMusic: Parameter numberSaliencePeaks: Invalid interval, should not contain space characters: "[1, 15]"
```
I get the same error even if I manually set numberSaliencePeaks which should be defaulted to 5 anyway

```
>>> tonic = essentia.standard.TonicIndianArtMusic(maxTonicFrequency=530,numberSaliencePeaks=5)(audio)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/antpc/anaconda3/lib/python3.8/site-packages/essentia/standard.py", line 44, in __init__
    self.configure(**kwargs)
  File "/home/antpc/anaconda3/lib/python3.8/site-packages/essentia/standard.py", line 64, in configure
    self.__configure__(**kwargs)
RuntimeError: Error while configuring TonicIndianArtMusic: Parameter numberSaliencePeaks: Invalid interval, should not contain space characters: "[1, 15]"
```
Python version 3.8.5
Ubuntu 18.04 LTS
Running in virtual environment

Please advice.

**Comment by alastair** [comment]
This has been fixed in the [master branch of essentia](https://github.com/MTG/essentia/commit/3958d0dfcbe5a965ee0e69b7b50784b8f1e38859). 
We will coordinate to release a new version on pypi with this fix included.

**Comment by dbogdanov** [comment]
We have updated the [PyPI Essentia wheels](https://pypi.org/project/essentia/) accordingly.
