### ISSUE TITLE
install to my own path 

### ISSUE THREAD

**Issue by Liujingxiu23** [MTG/essentia#1304]
I do config and install, everything seems ok unit the end of install

280/283] Linking build/src/libessentia.a
Waf: Leaving directory `/data/liangmin/Accompaniment/essentia/build'
Build failed
Traceback (most recent call last):
  File "/data/liangmin/Accompaniment/essentia/.waf3-2.0.25-767522112be77f8585812fcfaa08e805/waflib/Task.py", line 180, in process
    ret=self.run()
  File "/data/liangmin/Accompaniment/essentia/.waf3-2.0.25-767522112be77f8585812fcfaa08e805/waflib/Build.py", line 556, in run
    x.parent.mkdir()
  File "/data/liangmin/Accompaniment/essentia/.waf3-2.0.25-767522112be77f8585812fcfaa08e805/waflib/Node.py", line 188, in mkdir
    raise Errors.WafError('Could not create the directory %r'%self)
waflib.Errors.WafError: Could not create the directory /usr/local/lib64/pkgconfig

How can I install to my own path?

**Comment by dbogdanov** [comment]
Do you have user permissions to write to `/usr/local`? If not then run the installation command with `sudo`.

**Comment by Liujingxiu23** [comment]
Thank you for your reply!

I want to install to my own path using python waf since using pip， I meet the problem of "https://github.com/MTG/essentia/issues/690". But now I solve the problem using "from essentia import standard".
