### ISSUE TITLE
Issues with sample code

### ISSUE THREAD

**Issue by SimplicityGuy** [MTG/essentia#1317]
Hi there! I'm finding a few issues with the sample code from https://essentia.upf.edu/essentia_python_tutorial.html:
1. When loading the model:
using:
```python
model = es.TensorflowPredictMusiCNN(graphFilename="discogs/discogs-effnet-bs64-1.pb")
```
I get:
```python
[   INFO   ] TensorflowPredict: Successfully loaded graph file: `discogs/discogs-effnet-bs64-1.pb`
Traceback (most recent call last):
  File "/home/datum/Code/foo/foo.py", line 7, in <module>
    model = es.TensorflowPredictMusiCNN(graphFilename="discogs/discogs-effnet-bs64-1.pb")
  File "/home/datum/.local/lib/python3.9/site-packages/essentia/standard.py", line 44, in __init__
    self.configure(**kwargs)
  File "/home/datum/.local/lib/python3.9/site-packages/essentia/standard.py", line 64, in configure
    self.__configure__(**kwargs)
RuntimeError: Error while configuring TensorflowPredictMusiCNN: TensorflowPredict: 'model/Placeholder' is not a valid node name of this graph.
TensorflowPredict: Available node names are:
Const, Const_1, Const_2, Const_3, Const_4, Const_5, Const_6, Const_7, Const_8, Const_9, Const_10, Const_11, Const_12, Const_13, Const_14, Const_15, Const_16, Const_17, Const_18, Const_19, Const_20, Const_21, Const_22, Const_23, Const_24, Const_25, Const_26, Const_27, Const_28, Const_29, Const_30, Const_31, Const_32, Const_33, Const_34, Const_35, Const_36, Const_37, Const_38, Const_39, Const_40, Const_41, Const_42, Const_43, Const_44, Const_45, Const_46, Const_47, Const_48, Const_49, Const_50, Const_51, Const_52, Const_53, Const_54, Const_55, Const_56, Const_57, Const_58, Const_59, Const_60, Const_61, Const_62, Const_63, Const_64, Const_65, Const_66, Const_67, Const_68, Const_69, Const_70, Const_71, Const_72, Const_73, Const_74, Const_75, Const_76, Const_77, Const_78, Const_79, Const_80, Const_81, Const_82, Const_83, Const_84, Const_85, Const_86, Const_87, Const_88, Const_89, Const_90, Const_91, Const_92, Const_93, Const_94, Const_95, Const_96, Const_97, Const_98, Const_99, Const_100, Const_101, Const_102, Const_103, Const_104, Const_105, Const_106, Const_107, Const_108, Const_109, Const_110, Const_111, Const_112, Const_113, Const_114, Const_115, Const_116, Const_117, Const_118, Const_119, Const_120, Const_121, Const_122, Const_123, Const_124, Const_125, Const_126, Const_127, Const_128, Const_129, Const_130, Const_131, Const_132, Const_133, Const_134, Const_135, Const_136, Const_137, Const_138, Const_139, Const_140, Const_141, Const_142, Const_143, Const_144, Const_145, Const_146, Const_147, Const_148, Const_149, Const_150, Const_151, Const_152, Const_153, Const_154, Const_155, Const_156, Const_157, Const_158, Const_159, Const_160, Const_161, Const_162, Const_163, NoOp, Const_164, serving_default_melspectrogram, PartitionedCall, saver_filename, StatefulPartitionedCall, StatefulPartitionedCall_1.

Reconfigure this algorithm with valid node names as inputs and outputs before starting the processing.
```
To resolve this, I used:
```python
model = es.TensorflowPredictMusiCNN(graphFilename="discogs/discogs-effnet-bs64-1.pb", input="serving_default_melspectrogram", output="PartitionedCall:0")
```
2. When building the stream graph:
Using:
```python
    # create audio loader
    loader = es.MonoLoader(filename=filename)

    # create framecutter and add it to the streaming graph
    framecutter = es.FrameCutter(frameSize=1024, hopSize=512)
    loader.audio >> framecutter.signal
```
I get:
```python
Traceback (most recent call last):
  File "/home/datum/Code/foo/foo.py", line 70, in <module>
    genres_per_minute = get_genres_per_minute(argv[1])
  File "/home/datum/Code/foo/foo.py", line 35, in get_genres_per_minute
    loader.audio >> framecutter.signal
AttributeError: 'Algo' object has no attribute 'audio'
```
To resolve, I tried:
```python
loader.paramValue("audioStream") >> framecutter.signal
```
But then I get:
```python
Traceback (most recent call last):
  File "/home/datum/Code/foo/foo.py", line 70, in <module>
    genres_per_minute = get_genres_per_minute(argv[1])
  File "/home/datum/Code/foo/foo.py", line 34, in get_genres_per_minute
    loader.paramValue("audioStream") >> framecutter.signal
AttributeError: 'Algo' object has no attribute 'signal'
```

I stopped here since I'm probably down the wrong path.

**Comment by SimplicityGuy** [comment]
FWIW, I'm using `tensorflow-2.12.0`. No NVidia card, just CPU.

**Comment by SimplicityGuy** [comment]
I've made a few modifications to my code. Unfortunately, I was using a combination of `standard` and `streaming` APIs. This won't work as the `streaming` APIs require the build of a graph to run, whereas the `standard` APIs run per operation. As such some properties are exposed differently and the functionality of the APIs differ.

After working through those changes, I'm hitting a runtime issue.
```python
[   INFO   ] TensorflowPredict: Successfully loaded graph file: `discogs/discogs-effnet-bs64-1.pb`
[   INFO   ] On connection Resample::signal → Duration::signal:
[   INFO   ] BUFFER SIZE MISMATCH: max=3172 - asked for read size 4096
[   INFO   ] resizing buffer to 36040/4505
2023-03-26 19:53:28.170677: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 3699850000 Hz
Traceback (most recent call last):
  File "/home/datum/Code/foo/foo.py", line 61, in <module>
    genres_per_minute = get_genres_per_minute(argv[1])
  File "/home/datum/Code/foo/foo.py", line 54, in get_genres_per_minute
    run(loader)
  File "/home/datum/.local/lib/python3.9/site-packages/essentia/__init__.py", line 148, in run
    return _essentia.run(gen)
RuntimeError: TensorflowPredict: Error running the Tensorflow session. Input to reshape is a tensor with 17920 values, but the requested shape has 81920
	 [[{{node Reshape_16}}]]
```

I've tried this with multiple mp3s, and I get the same error.

My code:
```python
    filename = "my.mp3"
    json_file = "discogs/discogs-effnet-bs64-1.json"
    model_file = "discogs/discogs-effnet-bs64-1.pb"

    with open(json_file, "r") as f:
        metadata = load(f)

    input_layer = metadata["schema"]["inputs"][0]["name"]
    output_layer = metadata["schema"]["outputs"][0]["name"]

    window_type = "hann"
    sample_rate = 16000
    frame_size = 512
    hop_size = 256
    n_bands = 96
    patch_size = 64
    display_size = 10

    buffer_size = patch_size * hop_size

    pool = Pool()

    model = ess.TensorflowPredictMusiCNN(
        graphFilename=model_file,
        input=input_layer,
        output=output_layer,
    )

    loader = ess.MonoLoader(filename=filename, sampleRate=sample_rate)
    frame_cutter = ess.FrameCutter(frameSize=frame_size, hopSize=hop_size)
    windowing = ess.Windowing(type=window_type)
    spectrum = ess.Spectrum()
    spectral_centroid = ess.SpectralCentroidTime()
    duration = ess.Duration(sampleRate=sample_rate)

    loader.audio >> frame_cutter.signal
    frame_cutter.frame >> windowing.frame
    windowing.frame >> spectrum.frame
    spectrum.spectrum >> spectral_centroid.array
    loader.audio >> duration.signal
    loader.audio >> model.signal

    spectral_centroid.centroid >> (pool, "centroid")
    duration.duration >> (pool, "duration")
    model.predictions >> (pool, "predictions")

    run(loader)

    print(pool["duration"])
    print(pool["centroid"])
    print(pool["predictions"])
```

**Comment by SimplicityGuy** [comment]
Finally found this: https://github.com/MTG/essentia-replicate-demos/blob/023198b4e1b60f42017f58c3aabcec58d78fa98f/effnet-discogs/predict.py

Super useful! Thank you!
