### ISSUE TITLE
Import error when importing tensorflow with essentia

### ISSUE THREAD

**Issue by zuble** [MTG/essentia#1321]
Hi :)

So i [installed essentia](https://essentia.upf.edu/installing.html) following this steps:

```
git clone --recursive https://github.com/MTG/essentia.git && cd essentia

-dependencies:
    sudo apt-get install build-essential libeigen3-dev libyaml-dev libfftw3-dev libavcodec-dev libavformat-dev libavutil-dev libswresample-dev libsamplerate0-dev libtag1-dev libchromaprint-dev
    sudo apt-get install python3-dev python3-numpy-dev python3-numpy python3-yaml python3-six
    run sh @ src/3rdparty/tensorflow/setup_from_libtensorflow.sh

-compile:
     python3 waf configure --with-tensorflow --with-python --with-examples
     sudo python3 waf
     sudo python3 waf install

-make usable in anaconda
     find essentia package with same python as conda env used to compile 
     ls /usr/local/lib/python3.8/site-packages/
     conda develop /usr/local/lib/python3.8/site-packages/
```
I can use without a problem.

However when trying to import tensorflow together with essentia, 
```
import essentia
from essentia import standard as es

import tensorflow as tf
print("tf.version",tf.version.VERSION)
```
i get the following error:

```
essentia_version 2.1-beta6-dev 

essentia_file /usr/local/lib/python3.8/site-packages/essentia/__init__.py 

sys.path [ '/home/jtstudents/anaconda3/envs/zugpu/lib/python38.zip', '/home/jtstudents/anaconda3/envs/zugpu/lib/python3.8', '/home/jtstudents/anaconda3/envs/zugpu/lib/python3.8/lib-dynload', '/home/jtstudents/anaconda3/envs/zugpu/lib/python3.8/site-packages', '/usr/local/lib/python3.8/site-packages'] 

Traceback (most recent call last):
  File "/home/jtstudents/anaconda3/envs/zugpu/lib/python3.8/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/jtstudents/anaconda3/envs/zugpu/lib/python3.8/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/jtstudents/anaconda3/envs/zugpu/lib/python3.8/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/jtstudents/anaconda3/envs/zugpu/lib/python3.8/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/jtstudents/anaconda3/envs/zugpu/lib/python3.8/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /home/jtstudents/anaconda3/envs/zugpu/lib/python3.8/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: _ZN10tensorflow8OpKernel11TraceStringB5cxx11EPNS_15OpKernelContextEb

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_offl.py", line 10, in <module>
    import tensorflow as tf
  File "/home/jtstudents/anaconda3/envs/zugpu/lib/python3.8/site-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/home/jtstudents/anaconda3/envs/zugpu/lib/python3.8/site-packages/tensorflow/python/__init__.py", line 50, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/jtstudents/anaconda3/envs/zugpu/lib/python3.8/site-packages/tensorflow/python/pywrap_tensorflow.py", line 69, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/jtstudents/anaconda3/envs/zugpu/lib/python3.8/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/jtstudents/anaconda3/envs/zugpu/lib/python3.8/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/jtstudents/anaconda3/envs/zugpu/lib/python3.8/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/jtstudents/anaconda3/envs/zugpu/lib/python3.8/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/jtstudents/anaconda3/envs/zugpu/lib/python3.8/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /home/jtstudents/anaconda3/envs/zugpu/lib/python3.8/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: _ZN10tensorflow8OpKernel11TraceStringB5cxx11EPNS_15OpKernelContextEb

Failed to load the native TensorFlow runtime.
```

when importing the other way around,
```
import tensorflow as tf
print("tf.version",tf.version.VERSION)

import essentia
from essentia import standard as es

```
i get the following error:

```
tf.version 2.2.0
Traceback (most recent call last):
  File "runner_printer.py", line 7, in <module>
    import essentia
  File "/usr/local/lib/python3.8/site-packages/essentia/__init__.py", line 1, in <module>
    from . import _essentia
ImportError: /usr/local/lib/libtensorflow.so.2: undefined symbol: _ZNK10tensorflow6Device19IsRemoteCallAllowedEv
```

I think that in #1167 mentions some hints, but not the same error.

Any help or workaround would be awesome.

**Comment by zuble** [comment]
Added more info.

Following the idea of @palonso comment:

> The new essentia-tensorflow wheels are shipped with a monolithic build of TensorFlow 2.5 that doesn't interfere with TensorFlow's python package, which means that essentia-tensorflow is now compatible with any TensorFlow version in Python 3.7 to 3.9.

It should be possible to have tensorflow 2.2 and essentia working side by side.
But the error indicates that there is a mismatch between the version of TensorFlow when imported together with essentia.

**Comment by zuble** [comment]
So i just found that if essentia is loaded as a script call, instead of in the same file, it works.

For now this will do.

**Comment by palonso** [comment]
Hi @zuble,
great to see that you found a solution!

If you want to have essentia-tensorflow  and tensorflow in the same python process the best solution is to use Essentia from our python wheel: i.e., `pip install essentia-tensorflow` instead of building it.

Or, if you want to build essentia, use [src/3rdparty/tensorflow/setup_from_python.sh](https://github.com/MTG/essentia/blob/master/src/3rdparty/tensorflow/setup_from_python.sh). This script will configure essentia to be linked against the tensorflow cpp library contained in the tensorflow wheel currently installed.

**Comment by zuble** [comment]
hi again,
followed both solutions and from first one :

```
conda develop -n zugpu -u /usr/local/lib/python3.8/site-packages/  (unlink src essentia to conda env)
pip install essentia-tensorflow
```
got this error
```
 from essentia.standard import TensorflowPredictFSDSINet
ImportError: cannot import name 'TensorflowPredictFSDSINet' from 'essentia.standard' (/home/jtstudents/anaconda3/envs/zugpu/lib/python3.8/site-packages/essentia/standard.py)
```
which i believe that the Pypi whell isnt updated with the new Predict algorithm #1280

when trying the second option 
```
pip unnistall essentia-tensorflow
conda develop -n zugpu /usr/local/lib/python3.8/site-packages/ (linked again)
sudo ./setup_from_python.sh
```
gives me the following error
```
looking for the tensorflow python package...
Traceback (most recent call last):
  File "setup_tensorflow.py", line 51, in <module>
    import tensorflow
ModuleNotFoundError: No module named 'tensorflow'

During handling of the above exception, another exception occurred:
(...)
(nano setup_tensorflow.py)

raise(Exception('tensorflow is not available from this interpreter.\n'
                            'Suggestion: `pip install tensorflow`'))
```
tried to import tensorflow aside the script and all good
```
>>> import tensorflow
>>> tensorflow.__file__
'/home/jtstudents/anaconda3/envs/zugpu/lib/python3.8/site-packages/tensorflow/__init__.py'
```
could this be happening because of using [setup_from_libtensorflow.sh as a instalation step](https://essentia.upf.edu/installing.html) ? 

thanks in advance :)

**Comment by palonso** [comment]
you are right, `TensorflowPredictFSDSINet` is unavailable in the latest PyPI wheel. We are working on this now!

Regarding your build, the problem is that tensorflow is installed in your anaconda environment, which is not in the root's path. Since you run `./setup_from_python.sh` with `sudo`, tensorflow needs to be accessible by the root.  You could add your anaconda path to the root's python path or just `sudo pip install tensorflow`.

**Comment by dbogdanov** [comment]
>  you are right, TensorflowPredictFSDSINet is unavailable in the latest PyPI wheel. We are working on this now!

It should be available now :)

**Comment by zuble** [comment]
> you are right, `TensorflowPredictFSDSINet` is unavailable in the latest PyPI wheel. We are working on this now!
> 
> Regarding your build, the problem is that tensorflow is installed in your anaconda environment, which is not in the root's path. Since you run `./setup_from_python.sh` with `sudo`, tensorflow needs to be accessible by the root. You could add your anaconda path to the root's python path or just `sudo pip install tensorflow`.

was about to go into the docker path to solve the issue, but 
mucho obrigadooo :D

**Comment by zuble** [comment]
Hii
So after finding this #1328 , i went into the docker path.
From a tensorflow/tensorflow:2.2.0-gpu image , and following this steps:
```
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential libeigen3-dev libyaml-dev \
        libfftw3-dev libavcodec-dev libavformat-dev \
        libavutil-dev libswresample-dev libsamplerate0-dev \
        libtag1-dev libchromaprint-dev && \
    rm -rf /var/lib/apt/lists/*
    
RUN apt-get update && \
    apt-get install -y --no-install-recommends \        
        python3-dev python3-numpy-dev python3-numpy \
        python3-yaml python3-six && \
    rm -rf /var/lib/apt/lists/*

RUN git clone --recursive https://github.com/MTG/essentia.git /opt/essentia

## build
WORKDIR /opt/essentia
RUN python3 waf --help
RUN python3 -c "import sys;print(sys.path)"
RUN nohup sh src/3rdparty/tensorflow/setup_from_python.sh > /opt/essentia/fromtf220_cmdwafsg.out
RUN nohup python3 waf configure --with-tensorflow --with-python --with-examples --pythondir=/usr/local/lib/python3.6/dist-packages > /opt/essentia/fromtf220_cmdwafconfig.out  
RUN python3 waf -v
```
i get the following errors in the build , actually multiple outputs with the same, as i think the build is on multithread.
```
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyList_Sort'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyType_IsSubtype'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PySys_WriteStdout'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyObject_HasAttrString'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyDict_Keys'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyErr_Clear'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyErr_SetObject'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyNumber_Long'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyFloat_FromDouble'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyErr_Restore'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyTuple_Type'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyErr_Occurred'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyObject_CallMethodObjArgs'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyUnicode_FromFormat'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyErr_SetString'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyList_Append'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyType_Type'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyErr_NormalizeException'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `Py_DecRef'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyType_GenericNew'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyCapsule_Type'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyLong_AsLongLongAndOverflow'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyExc_IndexError'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyEval_SaveThread'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyObject_GC_UnTrack'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PySequence_Check'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyCapsule_Import'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyObject_CallMethod'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyCFunction_NewEx'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyErr_Fetch'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `_Py_CheckRecursiveCall'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyEval_RestoreThread'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyDict_Size'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyExc_MemoryError'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyObject_GetBuffer'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyCallable_Check'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PySequence_Size'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyTuple_GetItem'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyObject_Malloc'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyBool_Type'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyBytes_AsStringAndSize'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyTuple_New'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyExc_ImportError'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyObject_GenericGetAttr'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PySequence_Fast'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PySequence_Tuple'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyWeakref_NewRef'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyDict_SetItemString'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyComplex_AsCComplex'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyList_GetItem'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyUnicode_FromStringAndSize'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyObject_ClearWeakRefs'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyObject_Repr'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyObject_IsSubclass'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyCapsule_GetPointer'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyInstanceMethod_New'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyObject_RichCompareBool'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `_Py_NotImplementedStruct'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyObject_GetItem'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `Py_BuildValue'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyFloat_Type'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyExc_StopIteration'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyArg_UnpackTuple'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyLong_FromVoidPtr'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyList_New'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyObject_SetAttr'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyExc_RuntimeError'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyUnicode_FromString'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyErr_Print'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyExc_AssertionError'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `_Py_CheckRecursionLimit'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyLong_AsDouble'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyArg_ParseTupleAndKeywords'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyList_SetItem'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyCapsule_New'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyMapping_HasKey'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyComplex_RealAsDouble'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyTuple_SetItem'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyObject_Hash'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyObject_Call'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyDict_GetItem'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyImport_AddModule'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyUnicode_AsUTF8'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyObject_CallFunctionObjArgs'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyUnicode_AsASCIIString'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyBytes_FromStringAndSize'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyComplex_ImagAsDouble'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyModule_GetDict'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyExc_BufferError'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyGILState_Ensure'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyThreadState_Get'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyObject_Init'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `_PyObject_New'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PySet_Type'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `_Py_NoneStruct'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `_PyArg_NoKeywords'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyMapping_Size'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyImport_Import'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyModule_AddObject'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyObject_Free'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyExc_Exception'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyBool_FromLong'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyLong_AsLong'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyLong_AsLongAndOverflow'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `_Py_TrueStruct'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyLong_FromLongLong'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyFloat_AsDouble'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `Py_IsInitialized'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyObject_GetAttrString'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyErr_Format'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyObject_Str'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyUnicode_Concat'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyLong_FromLong'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyModule_Create2'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyExc_NotImplementedError'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyComplex_Type'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyType_FromSpecWithBases'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyErr_WriteUnraisable'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyTuple_Pack'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyBytes_AsString'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyLong_AsUnsignedLongLong'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyErr_ExceptionMatches'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyRun_SimpleStringFlags'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyExc_TypeError'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyType_Ready'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyObject_IsTrue'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyMapping_Keys'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyObject_GetAttr'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyList_Size'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyObject_GetIter'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyExc_AttributeError'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyExc_ValueError'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyImport_ImportModule'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `_Py_FalseStruct'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyObject_CallObject'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyObject_IsInstance'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyArg_ParseTuple'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyDict_Next'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyDict_New'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyGILState_Release'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PySequence_GetItem'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyNumber_Float'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyIter_Next'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyEval_CallObjectWithKeywords'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyUnicode_AsUTF8AndSize'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyTuple_Size'
/usr/local/lib/libpywrap_tensorflow_internal.so: undefined reference to `PyUnicode_InternFromString'
collect2: error: ld returned 1 exit status
```
[fromtf220_cmdwafconfig.log](https://github.com/MTG/essentia/files/11357231/fromtf220_cmdwafconfig.log)
[fromtf220_cmdwafsg.log](https://github.com/MTG/essentia/files/11357232/fromtf220_cmdwafsg.log)
[fromtf220_config.log](https://github.com/MTG/essentia/files/11357233/fromtf220_config.log)

So i tried the same except now from a different base image:
```
FROM nvidia/cuda:10.1-cudnn7-runtime-ubuntu18.04

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential git nano\                     
    libeigen3-dev libyaml-dev libfftw3-dev libavcodec-dev libavformat-dev \                      
    libavutil-dev libswresample-dev libsamplerate0-dev libtag1-dev libchromaprint-dev \
    python3-pip \                  
    python3-dev python3-numpy-dev python3-numpy python3-yaml python3-six \                         
&& rm -rf /var/lib/apt/lists/*

RUN python3 -m pip install --upgrade pip setuptools wheel && \
    python3 -m pip install tensorflow-gpu==2.2.0

ENV LANG=C.UTF-8
WORKDIR /opt/essentia
RUN python3 waf --help
RUN python3 -c "import sys;print(sys.path)"
RUN nohup sh src/3rdparty/tensorflow/setup_from_python.sh > /opt/essentia/fromnvidia_cmdwafsg.out
RUN nohup python3 waf configure --with-tensorflow --with-python --with-examples --pythondir=/usr/local/lib/python3.6/dist-packages > /opt/essentia/fromnvidia_cmdwafconfig.out 
RUN python3 waf -v
```
altough got aswell errors while building. 
[fromnvidia_cmdwafconfig.log](https://github.com/MTG/essentia/files/11357228/fromnvidia_cmdwafconfig.log)
[fromnvidia_cmdwafsg.log](https://github.com/MTG/essentia/files/11357229/fromnvidia_cmdwafsg.log)
[fromnvidia_config.log](https://github.com/MTG/essentia/files/11357230/fromnvidia_config.log)

I start to get out of ideas here, so any feedback from you would mean a lot.
Have a good weekend :)
