### ISSUE TITLE
Tensorflow not found

### ISSUE THREAD

**Issue by Galvo87** [MTG/essentia#1348]
I am trying to compile latest Essentia on a Ubuntu 22.04 box, with CUDA 11.8, CUDNN 8.6.0.163 and Tensorrt.
NVIDIA 525.125.06 driver, correctly reporting my RTX3090.
All necessary paths are included inside LD_LIBRARY_PATH, however when issueing `sudo ./src/3rdparty/tensorflow/setup_from_python.sh` inside essentia dir results in

`looking for the tensorflow python package...
Traceback (most recent call last):
  File "/home/developer/essentia/src/3rdparty/tensorflow/setup_tensorflow.py", line 51, in <module>
    import tensorflow
ModuleNotFoundError: No module named 'tensorflow'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/developer/essentia/src/3rdparty/tensorflow/setup_tensorflow.py", line 53, in <module>
    print(error.__class__.__name__ + ": " + error.message)
AttributeError: 'ModuleNotFoundError' object has no attribute 'message'`

it seems the script cannot find the Tensorflow installation... any hint please?

**Comment by palonso** [comment]
Hi @Galvo87,
Since you are using `setup_from_python.sh` with `sudo`. TensorFlow should be available on the root's python path.
You can achieve this by doing `sudo pip install tensorflow`.
