### ISSUE TITLE
Documentation build failure: No such file or directory: essentia_reference.py

### ISSUE THREAD

**Issue by foresto** [MTG/essentia#153]
The `doc` build target fails in the 2.1beta1 release. There are plenty of warnings throughout, and when it gets to the sphinx documentation, it says this:

```
******** BUILDING SPHINX DOCUMENTATION ********
Traceback (most recent call last):
  File "generate_reference.py", line 23, in <module>
    import essentia.standard
ImportError: No module named essentia.standard
sphinx-build -b html -d _build/doctrees   . _build/html
Making output directory...
Running Sphinx v1.2.2

Exception occurred:
  File "conf.py", line 168, in <module>
    execfile('essentia_reference.py')
IOError: [Errno 2] No such file or directory: 'essentia_reference.py'
The full traceback has been saved in /tmp/sphinx-err-EgvMAI.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://bitbucket.org/birkenfeld/sphinx/issues/>. Thanks!
make: *** [html] Error 1
******** MERGING DOCUMENTATION ********
'doc' finished successfully (1.355s)
```

The contents of /tmp/sphinx-err-EgvMAI.log:
```
# Sphinx version: 1.2.2
# Python version: 2.7.6
# Docutils version: 0.11 release
# Jinja2 version: 2.7.2
# Loaded extensions:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/cmdline.py", line 253, in main
    warningiserror, tags, verbosity, parallel)
  File "/usr/lib/python2.7/dist-packages/sphinx/application.py", line 107, in __init__
    confoverrides or {}, self.tags)
  File "/usr/lib/python2.7/dist-packages/sphinx/config.py", line 229, in __init__
    execfile_(filename, config)
  File "/usr/lib/python2.7/dist-packages/sphinx/util/pycompat.py", line 105, in execfile_
    exec code in _globals
  File "conf.py", line 168, in <module>
    execfile('essentia_reference.py')
IOError: [Errno 2] No such file or directory: 'essentia_reference.py'
```

**Comment by levivoelz** [comment]
I get the same issue. I tried updating my PYTHONPATH, reconfiguring and installing, updating system PATH.. Any ideas? Thanks!
