### ISSUE TITLE
examples error

### ISSUE THREAD

**Issue by gasper321** [MTG/essentia#244]
Hello.

I'm trying to run examples/out of the box extractor for essentia-2.0.1 using python. I navigate to src/examples/python/streaming_extractor/<something.py> (i tried using lowlevel.py).

So when i run **python lowlevel.py /path/to/input.wav /path/to/output.yaml**

i get 

gasper@gasper-P5KR:~/PycharmProjects/CmrljiTEST/examples_python/streaming_extractor$ python lowlevelspectral.py /home/gasper/audio2.wav /home/gasper/output.yaml
Traceback (most recent call last):
  File "lowlevelspectral.py", line 232, in <module>
    lowlevelExtractor = LowLevelSpectralExtractor()
  File "lowlevelspectral.py", line 115, in __init__
    pitch = PitchDetection(frameSize=frameSize)
NameError: global name 'PitchDetection' is not defined
gasper@gasper-P5KR:~/PycharmProjects/CmrljiTEST/examples_python/streaming_extractor$

I wasn't changing the code in any way (this is directly from 2.0.1 branch).

It seems to not find PitchDetection. I then tried removing PitchDetection from the lowlevel extractor. In that case, i got the error in essentia.run() (something with pitch sink missing i believe - i did not pursue this yet, since i was changing the source code of examples for this test).

@dbogdanov 
Any idea on what the problem might be? I have several problems with things not being found (Unresolved reference error is common), but when i run the tutorial code from http://essentia.upf.edu/documentation/python_tutorial.html, it seems to find most classes that are reported missing before...? Same goes for the example lowlevel.py, with the above exception. 

I thought about using mfcc features only, but i saw that mfcc extractor is commented as probably outdated and it is included under lowlevel.py.

Thanks for any help and best regards,

Gasper

**Comment by dbogdanov** [comment]
The out-of-box extractors are written in C++ and are in ```src/examples``` folder. 
```src/examples/python``` contains outdated python code that we are currently reviewing.
