### ISSUE TITLE
ValueError: vector

### ISSUE THREAD

**Issue by erikparr** [MTG/essentia#280]
After successful installation on Yosemite, I get the following error when trying the run_python_tests. I get the same error when I try the to run freesound essentia_example file. I'm building from the most recent master branch of essentia. I have no clue what this error means, any help would be appreciated.

Traceback (most recent call last):
  File "test/src/unittest/all_tests.py", line 242, in <module>
    essentia.standard._reloadAlgorithms()
  File "/usr/local/lib/python2.7/site-packages/essentia/standard.py", line 112, in _reloadAlgorithms
    _create_essentia_class(name, moduleName)
  File "/usr/local/lib/python2.7/site-packages/essentia/standard.py", line 29, in _create_essentia_class
    _algoInstance = _essentia.Algorithm(name)
ValueError: vector

**Comment by dbogdanov** [comment]
Which Freesound example file do you refer to?

**Comment by erikparr** [comment]
Thanks for the reply. I'm referring to freesound-python ( https://github.com/MTG/freesound-python ) essentia_example.py

This is the exact error i get on when I run essentia_example:

Traceback (most recent call last):
  File "essentia_example.py", line 2, in <module>
    from essentia.standard import *
  File "/usr/local/lib/python2.7/site-packages/essentia/standard.py", line 114, in <module>
    _reloadAlgorithms()
  File "/usr/local/lib/python2.7/site-packages/essentia/standard.py", line 112, in _reloadAlgorithms
    _create_essentia_class(name, moduleName)
  File "/usr/local/lib/python2.7/site-packages/essentia/standard.py", line 29, in _create_essentia_class
    _algoInstance = _essentia.Algorithm(name)
ValueError: vector

**Comment by yaizar** [comment]
I'm also in Yosemite & getting this when trying to import essentia.standard :(((

**Comment by jonmrjr** [comment]
Also happening for me on Yosemite.
However, it did not happen upon the very first time I imported that module. Only subsequent times.

**Comment by dbogdanov** [comment]
Cannot reproduce this using the latest master.
