### ISSUE TITLE
invalid syntax during ./waf config

### ISSUE THREAD

**Issue by rcrath** [MTG/essentia#387]
Get the following when I try to run ./waf configure.  Maybe because python 3 is my default?  if that is case plz tell me the trick to making it use python 2 :)  thanks.

````

[essentia]$./waf configure --mode=release --build-static --with-python --with-cpptests --with-examples --with-vamp 
Waf: The wscript in '/home/rich/git/essentia' is unreadable
Traceback (most recent call last):
  File "/home/rich/git/essentia/.waf3-1.7.9-16e1644c17ba46b94844133bac6e2a8c/waflib/Scripting.py", line 87, in waf_entry_point
    set_main_module(Context.run_dir+os.sep+Context.WSCRIPT_FILE)
  File "/home/rich/git/essentia/.waf3-1.7.9-16e1644c17ba46b94844133bac6e2a8c/waflib/Scripting.py", line 112, in set_main_module
    Context.g_module=Context.load_module(file_path)
  File "/home/rich/git/essentia/.waf3-1.7.9-16e1644c17ba46b94844133bac6e2a8c/waflib/Context.py", line 281, in load_module
    exec(compile(code,path,'exec'),module.__dict__)
  File "/home/rich/git/essentia/wscript", line 14
    except Exception, e:
                    ^
SyntaxError: invalid syntax

**Comment by nils-werner** [comment]
You can run `python2 ./waf` instead of just `./waf`.

**Comment by rcrath** [comment]
got further, but now failing with an error about swig.  will check other issues for that as I seem to remember something. thanks.  closing this.

**Comment by rcrath** [comment]
oops that error was for compiling gaia, not essentia, so never mind.  Have not tried essentia since I want to install Gaia first.
