### ISSUE TITLE
install error: osx 10.11.4

### ISSUE THREAD

**Issue by leozimmerman** [MTG/essentia#392]
When running ./waf install in an recently updated osx 10.11.4 system i get this errors:

> Build failed
> Traceback (most recent call last):
>   File "/Users/leo/Development/essentia/.waf-1.7.9-16e1644c17ba46b94844133bac6e2a8c/waflib/Task.py", line 123, in process
>     ret=self.run()
>   File "/Users/leo/Development/essentia/.waf-1.7.9-16e1644c17ba46b94844133bac6e2a8c/waflib/Task.py", line 47, in run
>     return m1(self)
>   File "/Users/leo/Development/essentia/.waf-1.7.9-16e1644c17ba46b94844133bac6e2a8c/waflib/Build.py", line 470, in run
>     return self.generator.exec_task()
>   File "/Users/leo/Development/essentia/.waf-1.7.9-16e1644c17ba46b94844133bac6e2a8c/waflib/Build.py", line 487, in exec_install_files
>     self.generator.bld.do_install(y.abspath(),destfile,self.chmod)
>   File "/Users/leo/Development/essentia/.waf-1.7.9-16e1644c17ba46b94844133bac6e2a8c/waflib/Build.py", line 535, in do_install

What could be the problem??

**Comment by leozimmerman** [comment]
Ive already found the solution. I needed to run the ./waf install commando with sudo: 

> sudo ./waf install
