### ISSUE TITLE
Numerical changes in descriptors values due to AudioLoader updates

### ISSUE THREAD

**Issue by dbogdanov** [MTG/essentia#401]
Since 064d53946193bf0fdcdb3b955f4136554aadf498 libavresamle is used to convert to  FLT format directly instead of converting to S16 and then scaling to -1., 1. float like it was done before. 

This change may introduce some *minor* differences in loaded audio and, therefore, descriptor values. The changes should be traceable running the unit tests. 

This issue is to report on known minor changes in descriptor values:
- MFCC (regression test fails)

This data will be obsolete once we create the robustness tests for all descriptors.

**Comment by dbogdanov** [comment]
```
FAIL: testRealCase (spectral.test_mfcc.TestMFCC)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dbogdanov/essentia/test/src/unittest/spectral/test_mfcc.py", line 97, in testRealCase
    self.assertAlmostEqualVector(mean(pool['mfcc'], 0), expected, 1.0e-5)
  File "/home/dbogdanov/essentia/test/src/unittest/essentia_test.py", line 115, in assertAlmostEqualVector
    self.assertAlmostEqual(val1, val2, precision)
  File "/home/dbogdanov/essentia/test/src/unittest/essentia_test.py", line 97, in assertAlmostEqual
    self.assert_(diff <= precision, 'Difference is %e while allowed precision is %e' % (diff, precision))
AssertionError: Difference is 1.266321e-05 while allowed precision is 1.000000e-05
```
