### ISSUE TITLE
Error running onsetdetection_example on 10.9.1- essentia::EssentiaException: Error encoding last frames

### ISSUE THREAD

**Issue by yyf** [MTG/essentia#45]
$ python onsetdetection_example.py 

usage: onsetdetection_example.py <audiofile>
$ python onsetdetection_example.py noise.wav
Loading audio file...
Computing onset detection functions...
Computing onset times...
Writing audio files to disk with onsets marked...
Traceback (most recent call last):
  File "onsetdetection_example.py", line 98, in <module>
    MonoWriter(filename = 'onsets_complex.mp3', format = 'mp3')(marker(audio))
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/essentia/standard.py", line 96, in __call__
    return self.compute(*args)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/essentia/standard.py", line 85, in compute
    results = self.__compute__(*convertedArgs)
RuntimeError: In MonoWriter.compute: Error encoding last frames
libc++abi.dylib: terminating with uncaught exception of type essentia::EssentiaException: Error encoding last frames
Abort trap: 6

However, there is an output file with onset annotation with beep. Any idea how to to resolve error? thanks.

**Comment by dbogdanov** [comment]
Cannot reproduce this issue with the latest master.
