### ISSUE TITLE
Help - ImportError: No module named essentia

### ISSUE THREAD

**Issue by mchijmma** [MTG/essentia#497]
Hello,

I haven't been able to install essentia, I have tried to follow some answers that I found in some closed issues but no luck so far.

I'm using Ubuntu 16.04

First I tried with essentia _2.1beta3_, then with _master_ ,  but I got the same results.

I'm using a conda enviroment which runs python 2.7

These are the steps I have folllowed:

`(python2) marco@marco-Satellite-P55t-B:~/Downloads/essentia-master$ sudo ./waf configure --mode=release --build-static --with-python --with-examples`

Result:

```
Setting top to                           : /home/marco/Downloads/essentia-master 
Setting out to                           : /home/marco/Downloads/essentia-master/build 
→ configuring the project in /home/marco/Downloads/essentia-master
→ Building in release mode
Checking for 'g++' (c++ compiler)        : /usr/bin/g++ 
Checking for 'gcc' (c compiler)          : /usr/bin/gcc 
Checking for program pkg-config          : /usr/bin/pkg-config 
Checking for 'libavcodec' >= 55.34.1     : yes 
Checking for 'libavformat'               : yes 
Checking for 'libavutil'                 : yes 
Checking for 'libavresample'             : yes 
Checking for 'samplerate'                : yes 
Checking for 'taglib' >= 1.9             : yes 
Checking for 'yaml-0.1'                  : yes 
Checking for 'fftw3f'                    : yes 
Checking for program python              : /usr/bin/python 
Checking for python version              : (2, 7, 12, 'final', 0) 
Checking for library python2.7 in LIBDIR : yes 
Checking for program /usr/bin/python-config,python2.7-config,python-config-2.7,python2.7m-config : /usr/bin/python-config 
Checking for header Python.h                                                                     : yes 

================================ CONFIGURATION SUMMARY ================================
- using FFTW for FFT

- fftw detected!
- FFmpeg / libav detected!
- libsamplerate (SRC) detected!
  The following algorithms will be included: ['MonoLoader', 'Resample', 'AudioWriter', 'EasyLoader', 'MonoWriter', 'EqloudLoader', 'AudioLoader']

- TagLib detected!
  The following algorithms will be included: ['MetadataReader']

- libyaml detected!
  The following algorithms will be included: ['YamlInput', 'YamlOutput']

- Essentia is configured without Gaia2.
  The following algorithms will be ignored: ['GaiaTransform']
  Examples requiring Gaia2 will be ignored

- Compiling 40 examples
  standard_beatsmarker, standard_mfcc, standard_onsetrate, standard_pitchyinfft, standard_fadedetection, standard_spectralcontrast, standard_rhythmtransform, standard_vibrato, standard_pitchmelodia, standard_notetranscription, standard_pitchdemo, streaming_extractor_music, streaming_beatsmarker, streaming_mfcc, streaming_gfcc, streaming_rhythmextractor_multifeature, streaming_beattracker_multifeature_mirex2013, streaming_onsetrate, streaming_panning, streaming_tuningfrequency, streaming_key, streaming_pitchyinfft, streaming_predominantmelody, streaming_pitchmelodia, streaming_vibrato, streaming_notetranscription, streaming_md5, streaming_memoryleak, streaming_extractor_freesound, standard_stft, streaming_stft, standard_predominantmask, standard_sinemodel, standard_sinesubtraction, standard_stochasticmodel, standard_spsmodel, standard_sprmodel, standard_harmonicmodel, standard_hpsmodel, standard_hprmodel
Building all the algorithms
Ignoring the following algorithms: IFFTA, GaiaTransform, IFFTK, FFTA, FFTK
Created algorithms registration file
=======================================================================================
'configure' finished successfully (0.393s)

```

Then:

`(python2) marco@marco-Satellite-P55t-B:~/Downloads/essentia-master$ sudo ./waf`

Result:

```
Waf: Entering directory `/home/marco/Downloads/essentia-master/build'
→ building from /home/marco/Downloads/essentia-master
→ building from /home/marco/Downloads/essentia-master/src
Building all the algorithms
Ignoring the following algorithms: IFFTA, GaiaTransform, FFTK, FFTA, IFFTK
Created algorithms registration file
→ building from /home/marco/Downloads/essentia-master/src/examples
→ building from /home/marco/Downloads/essentia-master/src/python
Waf: Leaving directory `/home/marco/Downloads/essentia-master/build'
'build' finished successfully (0.326s)
```

Then:

`(python2) marco@marco-Satellite-P55t-B:~/Downloads/essentia-master$ sudo ./waf install`

Result:

```
Waf: Entering directory `/home/marco/Downloads/essentia-master/build'
→ building from /home/marco/Downloads/essentia-master
→ building from /home/marco/Downloads/essentia-master/src
Building all the algorithms
Ignoring the following algorithms: IFFTA, GaiaTransform, FFTK, FFTA, IFFTK
Created algorithms registration file
→ building from /home/marco/Downloads/essentia-master/src/examples
→ building from /home/marco/Downloads/essentia-master/src/python
- install /usr/local/include/essentia/algorithm.h (from src/essentia/algorithm.h)
- install /usr/local/include/essentia/algorithmfactory.h (from src/essentia/algorithmfactory.h)
- install /usr/local/include/essentia/algorithmfactory_impl.h (from src/essentia/algorithmfactory_impl.h)
- install /usr/local/include/essentia/config.h (from src/essentia/config.h)
- install /usr/local/include/essentia/configurable.h (from src/essentia/configurable.h)
- install /usr/local/include/essentia/debugging.h (from src/essentia/debugging.h)
- install /usr/local/include/essentia/connector.h (from src/essentia/connector.h)
- install /usr/local/include/essentia/essentia.h (from src/essentia/essentia.h)
- install /usr/local/include/essentia/iotypewrappers.h (from src/essentia/iotypewrappers.h)
- install /usr/local/include/essentia/essentiamath.h (from src/essentia/essentiamath.h)
- install /usr/local/include/essentia/essentiautil.h (from src/essentia/essentiautil.h)
- install /usr/local/include/essentia/parameter.h (from src/essentia/parameter.h)
- install /usr/local/include/essentia/iotypewrappers_impl.h (from src/essentia/iotypewrappers_impl.h)
- install /usr/local/include/essentia/pool.h (from src/essentia/pool.h)
- install /usr/local/include/essentia/roguevector.h (from src/essentia/roguevector.h)
- install /usr/local/include/essentia/range.h (from src/essentia/range.h)
- install /usr/local/include/essentia/scheduler/graphutils.h (from src/essentia/scheduler/graphutils.h)
- install /usr/local/include/essentia/scheduler/network.h (from src/essentia/scheduler/network.h)
- install /usr/local/include/essentia/scheduler/networkparser.h (from src/essentia/scheduler/networkparser.h)
- install /usr/local/include/essentia/streamconnector.h (from src/essentia/streamconnector.h)
- install /usr/local/include/essentia/streaming/accumulatoralgorithm.h (from src/essentia/streaming/accumulatoralgorithm.h)
- install /usr/local/include/essentia/streaming/algorithms/copy.h (from src/essentia/streaming/algorithms/copy.h)
- install /usr/local/include/essentia/streaming/algorithms/devnull.h (from src/essentia/streaming/algorithms/devnull.h)
- install /usr/local/include/essentia/streaming/algorithms/fileoutput.h (from src/essentia/streaming/algorithms/fileoutput.h)
- install /usr/local/include/essentia/streaming/algorithms/diskwriter.h (from src/essentia/streaming/algorithms/diskwriter.h)
- install /usr/local/include/essentia/streaming/algorithms/poolstorage.h (from src/essentia/streaming/algorithms/poolstorage.h)
- install /usr/local/include/essentia/streaming/algorithms/ringbufferinput.h (from src/essentia/streaming/algorithms/ringbufferinput.h)
- install /usr/local/include/essentia/streaming/algorithms/ringbufferoutput.h (from src/essentia/streaming/algorithms/ringbufferoutput.h)
- install /usr/local/include/essentia/streaming/algorithms/ringbuffervectoroutput.h (from src/essentia/streaming/algorithms/ringbuffervectoroutput.h)
- install /usr/local/include/essentia/streaming/algorithms/vectorinput.h (from src/essentia/streaming/algorithms/vectorinput.h)
- install /usr/local/include/essentia/streaming/algorithms/vectoroutput.h (from src/essentia/streaming/algorithms/vectoroutput.h)
- install /usr/local/include/essentia/streaming/multiratebuffer.h (from src/essentia/streaming/multiratebuffer.h)
- install /usr/local/include/essentia/streaming/phantombuffer_impl.h (from src/essentia/streaming/phantombuffer_impl.h)
- install /usr/local/include/essentia/streaming/phantombuffer.h (from src/essentia/streaming/phantombuffer.h)
- install /usr/local/include/essentia/streaming/sinkbase.h (from src/essentia/streaming/sinkbase.h)
- install /usr/local/include/essentia/streaming/sink.h (from src/essentia/streaming/sink.h)
- install /usr/local/include/essentia/streaming/sinkproxy.h (from src/essentia/streaming/sinkproxy.h)
- install /usr/local/include/essentia/streaming/sourcebase.h (from src/essentia/streaming/sourcebase.h)
- install /usr/local/include/essentia/streaming/source.h (from src/essentia/streaming/source.h)
- install /usr/local/include/essentia/streaming/sourceproxy.h (from src/essentia/streaming/sourceproxy.h)
- install /usr/local/include/essentia/streaming/streamingalgorithm.h (from src/essentia/streaming/streamingalgorithm.h)
- install /usr/local/include/essentia/streaming/streamingalgorithmcomposite.h (from src/essentia/streaming/streamingalgorithmcomposite.h)
- install /usr/local/include/essentia/streaming/streamingalgorithmwrapper.h (from src/essentia/streaming/streamingalgorithmwrapper.h)
- install /usr/local/include/essentia/streamutil.h (from src/essentia/streamutil.h)
- install /usr/local/include/essentia/stringutil.h (from src/essentia/stringutil.h)
- install /usr/local/include/essentia/threading.h (from src/essentia/threading.h)
- install /usr/local/include/essentia/utils/MersenneTwister.h (from src/essentia/utils/MersenneTwister.h)
- install /usr/local/include/essentia/types.h (from src/essentia/types.h)
- install /usr/local/include/essentia/utils/asciidag.h (from src/essentia/utils/asciidag.h)
- install /usr/local/include/essentia/utils/asciidagparser.h (from src/essentia/utils/asciidagparser.h)
- install /usr/local/include/essentia/utils/audiocontext.h (from src/essentia/utils/audiocontext.h)
- install /usr/local/include/essentia/utils/atomic.h (from src/essentia/utils/atomic.h)
- install /usr/local/include/essentia/utils/bpfutil.h (from src/essentia/utils/bpfutil.h)
- install /usr/local/include/essentia/utils/betools.h (from src/essentia/utils/betools.h)
- install /usr/local/include/essentia/utils/bpmutil.h (from src/essentia/utils/bpmutil.h)
- install /usr/local/include/essentia/utils/ffmpegapi.h (from src/essentia/utils/ffmpegapi.h)
- install /usr/local/include/essentia/utils/metadatautils.h (from src/essentia/utils/metadatautils.h)
- install /usr/local/include/essentia/utils/jsonconvert.h (from src/essentia/utils/jsonconvert.h)
- install /usr/local/include/essentia/utils/output.h (from src/essentia/utils/output.h)
- install /usr/local/include/essentia/utils/peak.h (from src/essentia/utils/peak.h)
- install /usr/local/include/essentia/utils/ringbufferimpl.h (from src/essentia/utils/ringbufferimpl.h)
- install /usr/local/include/essentia/utils/tnt/jama_cholesky.h (from src/essentia/utils/tnt/jama_cholesky.h)
- install /usr/local/include/essentia/utils/synth_utils.h (from src/essentia/utils/synth_utils.h)
- install /usr/local/include/essentia/utils/tnt/jama_eig.h (from src/essentia/utils/tnt/jama_eig.h)
- install /usr/local/include/essentia/utils/tnt/jama_qr.h (from src/essentia/utils/tnt/jama_qr.h)
- install /usr/local/include/essentia/utils/tnt/jama_svd.h (from src/essentia/utils/tnt/jama_svd.h)
- install /usr/local/include/essentia/utils/tnt/jama_lu.h (from src/essentia/utils/tnt/jama_lu.h)
- install /usr/local/include/essentia/utils/tnt/tnt.h (from src/essentia/utils/tnt/tnt.h)
- install /usr/local/include/essentia/utils/tnt/tnt2essentiautils.h (from src/essentia/utils/tnt/tnt2essentiautils.h)
- install /usr/local/include/essentia/utils/tnt/tnt2vector.h (from src/essentia/utils/tnt/tnt2vector.h)
- install /usr/local/include/essentia/utils/tnt/tnt_array1d.h (from src/essentia/utils/tnt/tnt_array1d.h)
- install /usr/local/include/essentia/utils/tnt/tnt_array1d_utils.h (from src/essentia/utils/tnt/tnt_array1d_utils.h)
- install /usr/local/include/essentia/utils/tnt/tnt_array2d_utils.h (from src/essentia/utils/tnt/tnt_array2d_utils.h)
- install /usr/local/include/essentia/utils/tnt/tnt_array2d.h (from src/essentia/utils/tnt/tnt_array2d.h)
- install /usr/local/include/essentia/utils/tnt/tnt_array3d_utils.h (from src/essentia/utils/tnt/tnt_array3d_utils.h)
- install /usr/local/include/essentia/utils/tnt/tnt_array3d.h (from src/essentia/utils/tnt/tnt_array3d.h)
- install /usr/local/include/essentia/utils/tnt/tnt_cmat.h (from src/essentia/utils/tnt/tnt_cmat.h)
- install /usr/local/include/essentia/utils/tnt/tnt_fortran_array1d.h (from src/essentia/utils/tnt/tnt_fortran_array1d.h)
- install /usr/local/include/essentia/utils/tnt/tnt_fortran_array1d_utils.h (from src/essentia/utils/tnt/tnt_fortran_array1d_utils.h)
- install /usr/local/include/essentia/utils/tnt/tnt_fortran_array2d_utils.h (from src/essentia/utils/tnt/tnt_fortran_array2d_utils.h)
- install /usr/local/include/essentia/utils/tnt/tnt_fortran_array3d_utils.h (from src/essentia/utils/tnt/tnt_fortran_array3d_utils.h)
- install /usr/local/include/essentia/utils/tnt/tnt_fortran_array3d.h (from src/essentia/utils/tnt/tnt_fortran_array3d.h)
- install /usr/local/include/essentia/utils/tnt/tnt_fortran_array2d.h (from src/essentia/utils/tnt/tnt_fortran_array2d.h)
- install /usr/local/include/essentia/utils/tnt/tnt_math_utils.h (from src/essentia/utils/tnt/tnt_math_utils.h)
- install /usr/local/include/essentia/utils/tnt/tnt_sparse_matrix_csr.h (from src/essentia/utils/tnt/tnt_sparse_matrix_csr.h)
- install /usr/local/include/essentia/utils/tnt/tnt_i_refvec.h (from src/essentia/utils/tnt/tnt_i_refvec.h)
- install /usr/local/include/essentia/utils/tnt/tnt_stopwatch.h (from src/essentia/utils/tnt/tnt_stopwatch.h)
- install /usr/local/include/essentia/utils/tnt/tnt_subscript.h (from src/essentia/utils/tnt/tnt_subscript.h)
- install /usr/local/include/essentia/utils/tnt/tnt_vec.h (from src/essentia/utils/tnt/tnt_vec.h)
- install /usr/local/include/essentia/utils/tnt/tnt_version.h (from src/essentia/utils/tnt/tnt_version.h)
- install /usr/local/include/essentia/utils/yamlast.h (from src/essentia/utils/yamlast.h)
+ install /usr/local/include/essentia/version.h (from src/version.h)
- install /usr/local/lib/pkgconfig/essentia.pc (from build/essentia.pc)
- install /usr/local/lib/libessentia.a (from build/src/libessentia.a)
- install /usr/local/lib/python2.7/dist-packages/essentia/__init__.py (from src/python/essentia/__init__.py)
- install /usr/local/bin/essentia_standard_onsetrate (from build/src/examples/essentia_standard_onsetrate)
- install /usr/local/bin/essentia_standard_beatsmarker (from build/src/examples/essentia_standard_beatsmarker)
- install /usr/local/bin/essentia_standard_mfcc (from build/src/examples/essentia_standard_mfcc)
- install /usr/local/bin/essentia_standard_fadedetection (from build/src/examples/essentia_standard_fadedetection)
- install /usr/local/lib/python2.7/dist-packages/essentia/algorithms.py (from src/python/essentia/algorithms.py)
- install /usr/local/bin/essentia_standard_spectralcontrast (from build/src/examples/essentia_standard_spectralcontrast)
- install /usr/local/bin/essentia_standard_rhythmtransform (from build/src/examples/essentia_standard_rhythmtransform)
- install /usr/local/bin/essentia_standard_vibrato (from build/src/examples/essentia_standard_vibrato)
- install /usr/local/bin/essentia_standard_pitchdemo (from build/src/examples/essentia_standard_pitchdemo)
- install /usr/local/bin/essentia_streaming_extractor_music (from build/src/examples/essentia_streaming_extractor_music)
- install /usr/local/bin/essentia_streaming_beatsmarker (from build/src/examples/essentia_streaming_beatsmarker)
- install /usr/local/bin/essentia_streaming_mfcc (from build/src/examples/essentia_streaming_mfcc)
- install /usr/local/lib/python2.7/dist-packages/essentia/common.py (from src/python/essentia/common.py)
- install /usr/local/bin/essentia_streaming_gfcc (from build/src/examples/essentia_streaming_gfcc)
- install /usr/local/bin/essentia_streaming_beattracker_multifeature_mirex2013 (from build/src/examples/essentia_streaming_beattracker_multifeature_mirex2013)
- install /usr/local/bin/essentia_streaming_rhythmextractor_multifeature (from build/src/examples/essentia_streaming_rhythmextractor_multifeature)
- install /usr/local/bin/essentia_streaming_onsetrate (from build/src/examples/essentia_streaming_onsetrate)
- install /usr/local/bin/essentia_streaming_panning (from build/src/examples/essentia_streaming_panning)
- install /usr/local/bin/essentia_streaming_tuningfrequency (from build/src/examples/essentia_streaming_tuningfrequency)
- install /usr/local/lib/python2.7/dist-packages/essentia/essentia_extractor.py (from src/python/essentia/essentia_extractor.py)
- install /usr/local/bin/essentia_streaming_key (from build/src/examples/essentia_streaming_key)
- install /usr/local/bin/essentia_streaming_pitchyinfft (from build/src/examples/essentia_streaming_pitchyinfft)
- install /usr/local/bin/essentia_streaming_vibrato (from build/src/examples/essentia_streaming_vibrato)
- install /usr/local/bin/essentia_streaming_md5 (from build/src/examples/essentia_streaming_md5)
- install /usr/local/lib/python2.7/dist-packages/essentia/extractor/__init__.py (from src/python/essentia/extractor/__init__.py)
- install /usr/local/bin/essentia_streaming_extractor_freesound (from build/src/examples/essentia_streaming_extractor_freesound)
- install /usr/local/bin/essentia_standard_stft (from build/src/examples/essentia_standard_stft)
- install /usr/local/bin/essentia_streaming_stft (from build/src/examples/essentia_streaming_stft)
- install /usr/local/lib/python2.7/dist-packages/essentia/extractor/average_loudness.py (from src/python/essentia/extractor/average_loudness.py)
- install /usr/local/bin/essentia_standard_stochasticmodel (from build/src/examples/essentia_standard_stochasticmodel)
- install /usr/local/bin/essentia_standard_predominantmask (from build/src/examples/essentia_standard_predominantmask)
- install /usr/local/bin/essentia_standard_sinesubtraction (from build/src/examples/essentia_standard_sinesubtraction)
- install /usr/local/bin/essentia_standard_sinemodel (from build/src/examples/essentia_standard_sinemodel)
- install /usr/local/bin/essentia_standard_harmonicmodel (from build/src/examples/essentia_standard_harmonicmodel)
- install /usr/local/bin/essentia_standard_sprmodel (from build/src/examples/essentia_standard_sprmodel)
- install /usr/local/bin/essentia_standard_spsmodel (from build/src/examples/essentia_standard_spsmodel)
- install /usr/local/lib/python2.7/dist-packages/essentia/extractor/beats.py (from src/python/essentia/extractor/beats.py)
- install /usr/local/bin/essentia_standard_hprmodel (from build/src/examples/essentia_standard_hprmodel)
- install /usr/local/bin/essentia_standard_hpsmodel (from build/src/examples/essentia_standard_hpsmodel)
- install /usr/local/lib/python2.7/dist-packages/essentia/_essentia.so (from build/src/python/_essentia.so)
- install /usr/local/lib/python2.7/dist-packages/essentia/extractor/chords.py (from src/python/essentia/extractor/chords.py)
- install /usr/local/lib/python2.7/dist-packages/essentia/extractor/chords_dissonance_table.py (from src/python/essentia/extractor/chords_dissonance_table.py)
- install /usr/local/lib/python2.7/dist-packages/essentia/extractor/highlevel.py (from src/python/essentia/extractor/highlevel.py)
- install /usr/local/lib/python2.7/dist-packages/essentia/extractor/lowlevel.py (from src/python/essentia/extractor/lowlevel.py)
- install /usr/local/lib/python2.7/dist-packages/essentia/extractor/onsetdetection.py (from src/python/essentia/extractor/onsetdetection.py)
- install /usr/local/lib/python2.7/dist-packages/essentia/extractor/panning.py (from src/python/essentia/extractor/panning.py)
- install /usr/local/lib/python2.7/dist-packages/essentia/extractor/relativeioi.py (from src/python/essentia/extractor/relativeioi.py)
- install /usr/local/lib/python2.7/dist-packages/essentia/extractor/scales.py (from src/python/essentia/extractor/scales.py)
- install /usr/local/lib/python2.7/dist-packages/essentia/extractor/segmentation.py (from src/python/essentia/extractor/segmentation.py)
- install /usr/local/lib/python2.7/dist-packages/essentia/extractor/segmentation_bic.py (from src/python/essentia/extractor/segmentation_bic.py)
- install /usr/local/lib/python2.7/dist-packages/essentia/extractor/segmentation_max_energy.py (from src/python/essentia/extractor/segmentation_max_energy.py)
- install /usr/local/lib/python2.7/dist-packages/essentia/extractor/segmentation_simple.py (from src/python/essentia/extractor/segmentation_simple.py)
- install /usr/local/lib/python2.7/dist-packages/essentia/extractor/sfx.py (from src/python/essentia/extractor/sfx.py)
- install /usr/local/lib/python2.7/dist-packages/essentia/extractor/squeezeInto.py (from src/python/essentia/extractor/squeezeInto.py)
- install /usr/local/lib/python2.7/dist-packages/essentia/extractor/tempotap.py (from src/python/essentia/extractor/tempotap.py)
- install /usr/local/lib/python2.7/dist-packages/essentia/extractor/thumbnail.py (from src/python/essentia/extractor/thumbnail.py)
- install /usr/local/lib/python2.7/dist-packages/essentia/extractor/tonal.py (from src/python/essentia/extractor/tonal.py)
- install /usr/local/lib/python2.7/dist-packages/essentia/plotting.py (from src/python/essentia/plotting.py)
- install /usr/local/lib/python2.7/dist-packages/essentia/pool.py (from src/python/essentia/pool.py)
- install /usr/local/lib/python2.7/dist-packages/essentia/progress.py (from src/python/essentia/progress.py)
- install /usr/local/lib/python2.7/dist-packages/essentia/standard.py (from src/python/essentia/standard.py)
- install /usr/local/lib/python2.7/dist-packages/essentia/streaming.py (from src/python/essentia/streaming.py)
- install /usr/local/lib/python2.7/dist-packages/essentia/translate.py (from src/python/essentia/translate.py)
- install /usr/local/lib/python2.7/dist-packages/essentia/utils.py (from src/python/essentia/utils.py)
- install /usr/local/lib/python2.7/dist-packages/essentia/weka/__init__.py (from src/python/essentia/weka/__init__.py)
- install /usr/local/lib/python2.7/dist-packages/essentia/weka/arff2matlab.py (from src/python/essentia/weka/arff2matlab.py)
- install /usr/local/lib/python2.7/dist-packages/essentia/weka/convert_essentia_to_weka.py (from src/python/essentia/weka/convert_essentia_to_weka.py)
- install /usr/local/lib/python2.7/dist-packages/essentia/weka/wekafile.py (from src/python/essentia/weka/wekafile.py)
Waf: Leaving directory `/home/marco/Downloads/essentia-master/build'
'install' finished successfully (0.319s)
```

After the installation is successful I tried to import essentia:

```
(python2) marco@marco-Satellite-P55t-B:~/Downloads/essentia-master$ python
Python 2.7.12 |Anaconda 4.2.0 (64-bit)| (default, Jul  2 2016, 17:42:40) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import essentia
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named essentia
```

Based on one of the suggestions I have found, I tried the following:

```
>>> import sys
>>> sys.path.append("/usr/local/lib/python2.7/site-packages")
>>> import essentia
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/essentia/__init__.py", line 1, in <module>
    import _essentia
ImportError: /home/marco/anaconda3/envs/python2/lib/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /usr/lib/x86_64-linux-gnu/libtag.so.1)
>>> 
```

I had the same results when I tried to install it outside the conda environment.

Thanks in advance, I would really need to run essentia on a conda environment.

Best,

Marco

**Comment by alastair** [comment]
We don't support non-standard python installations such as conda.

However, it looks like your problem is that the configure step is using system python (`/usr/bin/python`) whereas when you run python as your local user you are using a different binary (`/home/marco/anaconda3/envs/python2/bin/python`), which is linked against a different version of glibc.

Don't run `waf configure` with sudo, because it won't find the conda python which you have in your local user's $PATH.

It also looks like conda bundles its own version of the c++ standard library, which taglib is not linked against. Your options here are to:
 * disable the `MetadataReader` algorithm if you don't need it (`waf configure --ignore-algos=MetadataReader)
 * compile taglib yourself, linking it against conda's std library
 * try and find a version of conda with the same version std library as your distribution
