### ISSUE TITLE
Can't compile Essentia on MacOs

### ISSUE THREAD

**Issue by kondor12** [MTG/essentia#515]
Hello
I try to do everything like in tutorial, but during the compiling essentia  whith the command 
./waf configure --mode=release --build-static --with-python --with-cpptests --with-examples --with-vamp

I have such error:

Checking for library python3.5 in LIBPATH_PYEMBED : Traceback (most recent call last):
  File "/Users/Kondor/Desktop/essentia-2.1_beta3/.waf3-1.7.9-16e1644c17ba46b94844133bac6e2a8c/waflib/Scripting.py", line 97, in waf_entry_point
    run_commands()
  File "/Users/Kondor/Desktop/essentia-2.1_beta3/.waf3-1.7.9-16e1644c17ba46b94844133bac6e2a8c/waflib/Scripting.py", line 153, in run_commands
    ctx=run_command(cmd_name)
  File "/Users/Kondor/Desktop/essentia-2.1_beta3/.waf3-1.7.9-16e1644c17ba46b94844133bac6e2a8c/waflib/Scripting.py", line 146, in run_command
    ctx.execute()
  File "/Users/Kondor/Desktop/essentia-2.1_beta3/.waf3-1.7.9-16e1644c17ba46b94844133bac6e2a8c/waflib/Configure.py", line 128, in execute
    super(ConfigurationContext,self).execute()
  File "/Users/Kondor/Desktop/essentia-2.1_beta3/.waf3-1.7.9-16e1644c17ba46b94844133bac6e2a8c/waflib/Context.py", line 87, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "/Users/Kondor/Desktop/essentia-2.1_beta3/.waf3-1.7.9-16e1644c17ba46b94844133bac6e2a8c/waflib/Context.py", line 128, in recurse
    user_function(self)
  File "/Users/Kondor/Desktop/essentia-2.1_beta3/wscript", line 251, in configure
    ctx.recurse('src')
  File "/Users/Kondor/Desktop/essentia-2.1_beta3/.waf3-1.7.9-16e1644c17ba46b94844133bac6e2a8c/waflib/Context.py", line 128, in recurse
    user_function(self)
  File "/Users/Kondor/Desktop/essentia-2.1_beta3/src/wscript", line 158, in configure
    ctx.recurse('python')
  File "/Users/Kondor/Desktop/essentia-2.1_beta3/.waf3-1.7.9-16e1644c17ba46b94844133bac6e2a8c/waflib/Context.py", line 128, in recurse
    user_function(self)
  File "/Users/Kondor/Desktop/essentia-2.1_beta3/src/python/wscript", line 17, in configure
    ctx.check_python_headers()
  File "/Users/Kondor/Desktop/essentia-2.1_beta3/.waf3-1.7.9-16e1644c17ba46b94844133bac6e2a8c/waflib/Configure.py", line 224, in fun
    return f(*k,**kw)
  File "/Users/Kondor/Desktop/essentia-2.1_beta3/.waf3-1.7.9-16e1644c17ba46b94844133bac6e2a8c/waflib/Tools/python.py", line 177, in check_python_headers
    result=conf.check(lib=name,uselib='PYEMBED',libpath=path,mandatory=False,msg='Checking for library %s in LIBPATH_PYEMBED'%name)
  File "/Users/Kondor/Desktop/essentia-2.1_beta3/.waf3-1.7.9-16e1644c17ba46b94844133bac6e2a8c/waflib/Configure.py", line 224, in fun
    return f(*k,**kw)
  File "/Users/Kondor/Desktop/essentia-2.1_beta3/.waf3-1.7.9-16e1644c17ba46b94844133bac6e2a8c/waflib/Tools/c_config.py", line 375, in check
    ret=self.run_c_code(*k,**kw)
  File "/Users/Kondor/Desktop/essentia-2.1_beta3/.waf3-1.7.9-16e1644c17ba46b94844133bac6e2a8c/waflib/Configure.py", line 224, in fun
    return f(*k,**kw)
  File "/Users/Kondor/Desktop/essentia-2.1_beta3/.waf3-1.7.9-16e1644c17ba46b94844133bac6e2a8c/waflib/Tools/c_config.py", line 459, in run_c_code
    bld.compile()
  File "/Users/Kondor/Desktop/essentia-2.1_beta3/.waf3-1.7.9-16e1644c17ba46b94844133bac6e2a8c/waflib/Build.py", line 196, in compile
    self.store()
  File "/Users/Kondor/Desktop/essentia-2.1_beta3/.waf3-1.7.9-16e1644c17ba46b94844133bac6e2a8c/waflib/Utils.py", line 386, in f
    ret=fun(*k,**kw)
  File "/Users/Kondor/Desktop/essentia-2.1_beta3/.waf3-1.7.9-16e1644c17ba46b94844133bac6e2a8c/waflib/Build.py", line 170, in store
    cPickle.dump(data,f,-1)
AttributeError: Can't pickle local object 'Context.__init__.<locals>.node_class'

OS X, essentia 2.1 beta 3
Please, help!

**Comment by dbogdanov** [comment]
Can you try compiling Essentia from the master branch?  In your case the build script is using python3. We've added support for building with python3 recently.
