### ISSUE TITLE
Could not install the file '/usr/local/lib/libessentia.so'

### ISSUE THREAD

**Issue by I159** [MTG/essentia#563]
Couldn't find any solution for that issue.

I'm using Ubuntu 16.04 LTS (desktop) and trying to install Essentia with this http://essentia.upf.edu/documentation/installing.html guide. Configuration and build done well but installation is failed:

```
./waf install
Waf: Entering directory `/home/ipekelnyi/Downloads/essentia/build'
→ building from /home/ipekelnyi/Downloads/essentia
→ building from /home/ipekelnyi/Downloads/essentia/src
Building all the algorithms
Ignoring the following algorithms: IFFTA, GaiaTransform, FFTK, FFTA, IFFTK
Created algorithms registration file
→ building from /home/ipekelnyi/Downloads/essentia/src/examples
→ building from /home/ipekelnyi/Downloads/essentia/src/python
+ install /usr/local/lib/libessentia.so (from build/src/libessentia.so)
Waf: Leaving directory `/home/ipekelnyi/Downloads/essentia/build'
Build failed
Traceback (most recent call last):
  File "/home/ipekelnyi/Downloads/essentia/.waf-1.9.5-52c80071ec5dbdb10277fb2f9cd81ba9/waflib/Task.py", line 145, in process
    ret=self.run()
  File "/home/ipekelnyi/Downloads/essentia/.waf-1.9.5-52c80071ec5dbdb10277fb2f9cd81ba9/waflib/Build.py", line 557, in run
    fun(x.abspath(),y.abspath(),x.path_from(launch_node))
  File "/home/ipekelnyi/Downloads/essentia/.waf-1.9.5-52c80071ec5dbdb10277fb2f9cd81ba9/waflib/Build.py", line 593, in do_install
    raise Errors.WafError('Could not install the file %r'%tgt,e)
WafError: Could not install the file '/usr/local/lib/libessentia.so'

```
What could cause the issue? And how to solve it?
Thanks!

**Comment by alastair** [comment]
Did you run `waf install` with sudo?

**Comment by I159** [comment]
Sorry, it was my wheel problem. Fixed and installation works well. Thanks for care!
