### ISSUE TITLE
Cross compile under Linux Subsystem for windows configure fails

### ISSUE THREAD

**Issue by Mereep** [MTG/essentia#577]
Hello,

I'm trying to get essentia (with python) running under windows. I tried to follow the tutorial at the website and got to the point where I have to configure the project.

I use following command:
`./waf configure --mode=release --build-static --with-python --with-static-examples --with-vamp --cross-compile-mingw32`

and get following output (last lines poi):

```
./waf configure --mode=release --build-static --with-python --with-static-examples --cross-compile-mingw32
Setting top to                           : /mnt/c/Users/richard/Downloads/essentia-master/essentia-master
Setting out to                           : /mnt/c/Users/richard/Downloads/essentia-master/essentia-master/build
→ configuring the project in /mnt/c/Users/richard/Downloads/essentia-master/essentia-master
→ Building in release mode
→ Cross-compiling for Windows with MinGW: search for pre-built dependencies in 'packaging/win32_3rdparty'
Checking for program 'i686-w64-mingw32-gcc' : /usr/bin/i686-w64-mingw32-gcc
Checking for program 'i686-w64-mingw32-g++' : /usr/bin/i686-w64-mingw32-g++
Checking for program 'i686-w64-mingw32-ar'  : /usr/bin/i686-w64-mingw32-ar
Checking for 'g++' (C++ compiler)           : /usr/bin/i686-w64-mingw32-g++
Checking for 'gcc' (C compiler)             : /usr/bin/i686-w64-mingw32-gcc
Checking for program 'pkg-config'           : /usr/bin/pkg-config
Checking for 'libavcodec' >= 55.34.1        : yes
Checking for 'libavformat'                  : yes
Checking for 'libavutil'                    : yes
Checking for 'libavresample'                : yes
Checking for 'samplerate'                   : yes
Checking for 'taglib' >= 1.9                : yes
Checking for 'yaml-0.1'                     : yes
Checking for 'fftw3f'                       : yes
WARNING: Use --with-static-examples flag instead of --with-examples for cross-compilation with MinGW
Checking for 'gcc' (C compiler)             : /usr/bin/i686-w64-mingw32-gcc
Checking for program 'python'               : /usr/bin/python
Checking for python version >= 2.7.0        : 2.7.6
python-config                               : /usr/bin/python-config
Asking python-config for pyembed '--cflags --libs --ldflags' flags : yes
Testing pyembed configuration                                      : Could not build a python embedded interpreter
Testing pyembed configuration                                      : Could not build a python embedded interpreter
The configuration failed
(complete log in /mnt/c/Users/richard/Downloads/essentia-master/essentia-master/build/config.log)
```
Here is the part in the logfile which might be of interest:
```
Could not build a python embedded interpreter
from /mnt/c/Users/richard/Downloads/essentia-master/essentia-master/src/python: The configuration failed
------------------------------------------------------------------
Testing pyembed configuration
==>

#include <Python.h>
#ifdef __cplusplus
extern "C" {
#endif
        void Py_Initialize(void);
        void Py_Finalize(void);
#ifdef __cplusplus
}
#endif
int main(int argc, char **argv)
{
   (void)argc; (void)argv;
   Py_Initialize();
   Py_Finalize();
   return 0;
}

<==
[1/2] Compiling build/.conf_check_1d179c3d3aad3c2a5543940ee242cd9d/test.cpp

['/usr/bin/i686-w64-mingw32-g++', '-static-libgcc', '-static-libstdc++', '-DYAML_DECLARE_STATIC', '-DTAGLIB_STATIC', '-fno-strict-aliasing', '-fstack-protector', '-fwrapv', '-I/usr/include/python2.7', '-I/usr/include/x86_64-linux-gnu/python2.7', '-DHAVE_AVCODEC=1', '-DHAVE_AVFORMAT=1', '-DHAVE_AVUTIL=1', '-DHAVE_AVRESAMPLE=1', '-DHAVE_SAMPLERATE=1', '-DHAVE_TAGLIB=1', '-DHAVE_YAML=1', '-DHAVE_FFTW=1', '-D__STDC_CONSTANT_MACROS', '-DPYTHONDIR="/usr/local/lib/python2.7/dist-packages"', '-DPYTHONARCHDIR="/usr/local/lib/python2.7/dist-packages"', '-D_FORTIFY_SOURCE=2', '-DNDEBUG', '../test.cpp', '-c', '-o/mnt/c/Users/richard/Downloads/essentia-master/essentia-master/build/.conf_check_1d179c3d3aad3c2a5543940ee242cd9d/testbuild/test.cpp.1.o']
err: In file included from /usr/include/python2.7/Python.h:8:0,
                 from ../test.cpp:2:
/usr/include/python2.7/pyconfig.h:78:3: error: #error unknown multiarch location for pyconfig.h
 # error unknown multiarch location for pyconfig.h
   ^
In file included from /usr/include/python2.7/pyport.h:4:0,
                 from /usr/include/python2.7/Python.h:58,
                 from ../test.cpp:2:
/usr/include/python2.7/pyconfig.h:78:3: error: #error unknown multiarch location for pyconfig.h
 # error unknown multiarch location for pyconfig.h
   ^
In file included from /usr/include/python2.7/pymath.h:4:0,
                 from /usr/include/python2.7/Python.h:77,
                 from ../test.cpp:2:
/usr/include/python2.7/pyconfig.h:78:3: error: #error unknown multiarch location for pyconfig.h
 # error unknown multiarch location for pyconfig.h
   ^

from /mnt/c/Users/richard/Downloads/essentia-master/essentia-master/src/python: Test does not build: Traceback (most recent call last):
  File "/mnt/c/Users/richard/Downloads/essentia-master/essentia-master/.waf-1.9.5-52c80071ec5dbdb10277fb2f9cd81ba9/waflib/Configure.py", line 324, in run_build
    bld.compile()
  File "/mnt/c/Users/richard/Downloads/essentia-master/essentia-master/.waf-1.9.5-52c80071ec5dbdb10277fb2f9cd81ba9/waflib/Build.py", line 181, in compile
    raise Errors.BuildError(self.producer.error)
BuildError: Build failed
 -> task in 'testprog' failed with exit status 1 (run with -v to display more information)

Could not build a python embedded interpreter
from /mnt/c/Users/richard/Downloads/essentia-master/essentia-master/src/python: The configuration failed
```

Idk if I missed something or have to tell python to be multiarch also. Would be way more simple if there would be some precompiled windows binaries (No offence) ;-)

**Comment by dbogdanov** [comment]
The easiest (and the only) current way to run Essentia in python on Windows  is to [use bash on ubuntu](http://essentia.upf.edu/documentation/installing.html#building-essentia-on-windows-10-via-bash-on-ubuntu). No need to cross-compile from linux.

**Comment by Mereep** [comment]
That essentially means, it is not possible to run essentia under native windows at the time of writing?

**Comment by dbogdanov** [comment]
Python bindings - no

**Comment by Mereep** [comment]
Ok, thanks for the answer. Still, it would be nice if this was mentioned somewhere in the docs.
