### ISSUE TITLE
dyld: Library not loaded on OS X 10.12.4 

### ISSUE THREAD

**Issue by yyf** [MTG/essentia#591]
Just updated my os to 10.12.4, and it broke my ipython/essentia environment. So I tried to reinstall essentia. I went through the installation and it compiled successfully. 

Tried to run ./waf run_tests after updating my OS to 10.12.4, but having the following errors: 

`dyld: Library not loaded: /System/Library/Frameworks/Jackmp.framework/Versions/A/Jackmp
  Referenced from: /usr/local/opt/ffmpeg/lib/libavformat.57.dylib
  Reason: image not found
'run_tests' finished successfully (0.014s)`

Running ./waf run_python_tests gives the following: 

`Traceback (most recent call last):
  File "test/src/unittest/all_tests.py", line 27, in <module>
    import essentia
  File "/Users/yuanyifan/Code/Essentia/essentia-2.1_beta3/build/python/essentia/__init__.py", line 1, in <module>
    import _essentia
ImportError: dlopen(/Users/yuanyifan/Code/Essentia/essentia-2.1_beta3/build/python/essentia/_essentia.so, 2): Library not loaded: /System/Library/Frameworks/Jackmp.framework/Versions/A/Jackmp
  Referenced from: /usr/local/opt/ffmpeg/lib/libavformat.57.dylib
  Reason: image not found
'run_python_tests' finished successfully (0.266s)`

Any special config needed for maxOS Sierra? 

Thanks.

**Comment by yyf** [comment]
brew update and upgrade solved the issue. have essentia working now on 10.12.4. 

Some test logs after successful installation: 

Ran ./waf run_tests and got 7 failed tests

`
[----------] Global test environment tear-down
[==========] 131 tests from 16 test cases ran. (213 ms total)
[  PASSED  ] 124 tests.
[  FAILED  ] 7 tests, listed below:
[  FAILED  ] AudioLoader.SimpleLoad
[  FAILED  ] AudioLoader.SampleFormatConversion
[  FAILED  ] Network.SimpleVisibleNetwork
[  FAILED  ] Network.ExecutionNetworkWithComposite
[  FAILED  ] Scheduler.SourceProxyFork
[  FAILED  ] TreeTraversal.DepthFirstMap
[  FAILED  ] TreeTraversal.DepthFirstSearch

 7 FAILED TESTS
'run_tests' finished successfully (0.264s)`

Ran ./waf run_python_tests the first time and it crashed python.
