### ISSUE TITLE
Fails to install on Arch Linux with Python3.6

### ISSUE THREAD

**Issue by martmists** [MTG/essentia#677]
Trying to install the recommended version: `v2.1_beta3`

Output of `./waf configure --build-static --with-vamp --with-python`:

```
Setting top to                           : /home/mart/git/essentia 
Setting out to                           : /home/mart/git/essentia/build 
â configuring the project in /home/mart/git/essentia
â Building in release mode
Checking for 'g++' (c++ compiler)        : /usr/bin/g++ 
Checking for 'gcc' (c compiler)          : /usr/bin/gcc 
Checking for program pkg-config          : /usr/bin/pkg-config 
Checking for 'libavcodec' >= 55.34.1     : yes 
Checking for 'libavformat'               : yes 
Checking for 'libavutil'                 : yes 
Checking for 'libavresample'             : yes 
Checking for 'samplerate'                : yes 
Checking for 'taglib' >= 1.9             : yes 
Checking for 'yaml-0.1'                  : yes 
Checking for 'fftw3f'                    : yes 
Checking for program python              : /usr/bin/python 
Checking for python version              : (3, 6, 4, 'final', 0) 
Checking for library python3.6 in LIBDIR : Traceback (most recent call last):
  File "/home/mart/git/essentia/.waf3-1.7.9-16e1644c17ba46b94844133bac6e2a8c/waflib/Scripting.py", line 97, in waf_entry_point
    run_commands()
  File "/home/mart/git/essentia/.waf3-1.7.9-16e1644c17ba46b94844133bac6e2a8c/waflib/Scripting.py", line 153, in run_commands
    ctx=run_command(cmd_name)
  File "/home/mart/git/essentia/.waf3-1.7.9-16e1644c17ba46b94844133bac6e2a8c/waflib/Scripting.py", line 146, in run_command
    ctx.execute()
  File "/home/mart/git/essentia/.waf3-1.7.9-16e1644c17ba46b94844133bac6e2a8c/waflib/Configure.py", line 128, in execute
    super(ConfigurationContext,self).execute()
  File "/home/mart/git/essentia/.waf3-1.7.9-16e1644c17ba46b94844133bac6e2a8c/waflib/Context.py", line 87, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "/home/mart/git/essentia/.waf3-1.7.9-16e1644c17ba46b94844133bac6e2a8c/waflib/Context.py", line 128, in recurse
    user_function(self)
  File "/home/mart/git/essentia/wscript", line 251, in configure
    ctx.recurse('src')
  File "/home/mart/git/essentia/.waf3-1.7.9-16e1644c17ba46b94844133bac6e2a8c/waflib/Context.py", line 128, in recurse
    user_function(self)
  File "/home/mart/git/essentia/src/wscript", line 158, in configure
    ctx.recurse('python')
  File "/home/mart/git/essentia/.waf3-1.7.9-16e1644c17ba46b94844133bac6e2a8c/waflib/Context.py", line 128, in recurse
    user_function(self)
  File "/home/mart/git/essentia/src/python/wscript", line 17, in configure
    ctx.check_python_headers()
  File "/home/mart/git/essentia/.waf3-1.7.9-16e1644c17ba46b94844133bac6e2a8c/waflib/Configure.py", line 224, in fun
    return f(*k,**kw)
  File "/home/mart/git/essentia/.waf3-1.7.9-16e1644c17ba46b94844133bac6e2a8c/waflib/Tools/python.py", line 181, in check_python_headers
    result=conf.check(lib=name,uselib='PYEMBED',libpath=path,mandatory=False,msg='Checking for library %s in LIBDIR'%name)
  File "/home/mart/git/essentia/.waf3-1.7.9-16e1644c17ba46b94844133bac6e2a8c/waflib/Configure.py", line 224, in fun
    return f(*k,**kw)
  File "/home/mart/git/essentia/.waf3-1.7.9-16e1644c17ba46b94844133bac6e2a8c/waflib/Tools/c_config.py", line 375, in check
    ret=self.run_c_code(*k,**kw)
  File "/home/mart/git/essentia/.waf3-1.7.9-16e1644c17ba46b94844133bac6e2a8c/waflib/Configure.py", line 224, in fun
    return f(*k,**kw)
  File "/home/mart/git/essentia/.waf3-1.7.9-16e1644c17ba46b94844133bac6e2a8c/waflib/Tools/c_config.py", line 459, in run_c_code
    bld.compile()
  File "/home/mart/git/essentia/.waf3-1.7.9-16e1644c17ba46b94844133bac6e2a8c/waflib/Build.py", line 196, in compile
    self.store()
  File "/home/mart/git/essentia/.waf3-1.7.9-16e1644c17ba46b94844133bac6e2a8c/waflib/Utils.py", line 386, in f
    ret=fun(*k,**kw)
  File "/home/mart/git/essentia/.waf3-1.7.9-16e1644c17ba46b94844133bac6e2a8c/waflib/Build.py", line 170, in store
    cPickle.dump(data,f,-1)
AttributeError: Can't pickle local object 'Context.__init__.<locals>.node_class'
```

**Comment by dbogdanov** [comment]
Please, install the master branch for python3 support.
