### ISSUE TITLE
Could not build a python embedded interpreter, g++ error 

### ISSUE THREAD

**Issue by kyungyunlee** [MTG/essentia#688]
I have cloned the master branch and ran this installation command on linux server.
```
./waf configure --build-static --with-python --with-cpptests --with-examples --with-vamp
```
Then, I get an error message about the python embedded inpreter and my config.log file shows this.
There seems like this error happend with python2 in the past, but has anyone experienced or know about how to resolve this error?

I feel like its related to gcc (I have gcc 5.4.0) , but I am afraid that updating gcc might cause further conflicts with other programs :(
Does the master branch version require gcc 6?

p.s I tried the beta3 version and it causes the same error as #681

Thanks

```
------------------------------------------------------------------
Testing pyembed configuration
==>

#include <Python.h>
#ifdef __cplusplus
extern "C" {
#endif
	void Py_Initialize(void);
	void Py_Finalize(void);
#ifdef __cplusplus
}
#endif
int main(int argc, char **argv)
{
   (void)argc; (void)argv;
   Py_Initialize();
   Py_Finalize();
   return 0;
}

<==
[1/2] Compiling [32mbuild/.conf_check_ceb5ca3ab697f46231c2cc8b404d74f2/test.cpp[0m

['/usr/bin/g++', '-pipe', '-Wall', '-msse', '-msse2', '-mfpmath=sse', '-O2', '-fPIC', '-pthread', '-march=nocona', '-mtune=haswell', '-ftree-vectorize', '-fPIC', '-fstack-protector-strong', '-fno-plt', '-O3', '-fuse-linker-plugin', '-ffat-lto-objects', '-flto-partition=none', '-flto', '-fwrapv', '-O3', '-I../../../../anaconda3/envs/tensorflow/include/python3.6m', '-I../../../../anaconda3/envs/tensorflow/include', '-DHAVE_AVCODEC=1', '-DHAVE_AVFORMAT=1', '-DHAVE_AVUTIL=1', '-DHAVE_AVRESAMPLE=1', '-DHAVE_SAMPLERATE=1', '-DHAVE_TAGLIB=1', '-DHAVE_YAML=1', '-DHAVE_FFTW=1', '-DHAVE_LIBCHROMAPRINT=1', '-D__STDC_CONSTANT_MACROS', '-DPYTHONDIR="/usr/local/lib/python3.6/site-packages"', '-DPYTHONARCHDIR="/usr/local/lib/python3.6/site-packages"', '-DNDEBUG', '../test.cpp', '-c', '-o/home/kylee/essentia/build/.conf_check_ceb5ca3ab697f46231c2cc8b404d74f2/testbuild/test.cpp.1.o', '-fPIC']
err: g++: error: unrecognized command line option ‘-fno-plt’

from /home/kylee/essentia/src/python: Test does not build: Traceback (most recent call last):
  File "/home/kylee/essentia/.waf3-1.9.11-af9ceda667eab9a2b3fb893b34583f23/waflib/Configure.py", line 327, in run_build
    bld.compile()
  File "/home/kylee/essentia/.waf3-1.9.11-af9ceda667eab9a2b3fb893b34583f23/waflib/Build.py", line 186, in compile
    raise Errors.BuildError(self.producer.error)
waflib.Errors.BuildError: Build failed
 -> task in 'testprog' failed with exit status 1 (run with -v to display more information)

Could not build a python embedded interpreter
from /home/kylee/essentia/src/python: The configuration failed
 
```

I faced some some issues with building for python3 (without anaconda env) as well. 
But building by not using anaconda && using python2 works...and I will just use this for now :(

**Comment by hurgdburg** [comment]
Have you resolved this issue? I'm getting the same problem.

**Comment by kyungyunlee** [comment]
Unfortunately no. I refrained from using conda python3 and used local python2 instead..

**Comment by dbogdanov** [comment]
Closing this, as you can now do ```pip install essentia``` on Linux.
