### ISSUE TITLE
Unable to pickle essentia Algorithms

### ISSUE THREAD

**Issue by JPery** [MTG/essentia#763]
I've tried to pickle some instantiated algorithms (instantiating them in different iterations is much time consuming) but using pickle.dump it throws a TypeError:

```
Traceback (most recent call last):
  File "~/FeatureExtractor/test.py", line 7, in <module>
    pickle.dump(algorithm, open("a.txt", "w"))
  File "/usr/lib/python2.7/pickle.py", line 1376, in dump
    Pickler(file, protocol).dump(obj)
  File "/usr/lib/python2.7/pickle.py", line 224, in dump
    self.save(obj)
  File "/usr/lib/python2.7/pickle.py", line 306, in save
    rv = reduce(self.proto)
  File "/usr/lib/python2.7/copy_reg.py", line 71, in _reduce_ex
    state = base(self)
TypeError: argument 1 must be string, not Algo
```

What can I do here?
Thanks for your attention

**Comment by dbogdanov** [comment]
The Essentia's python extension currently does not support pickle. To do that we'll need  to implement a __reduce__() method along with __getstate__() and __setstate__() [PyAlgorithm methods](https://github.com/MTG/essentia/blob/master/src/python/pyalgorithm.cpp#L477). 

https://www.python.org/dev/peps/pep-0307/

We can add this to our wishlist. A pull request is welcome.

**Comment by 00sapo** [comment]
Just created a commit that could maybe solve the problem for algorithms that have no memory of previous applications (do exist such algorithms?)

https://github.com/MTG/essentia/commit/bb8365e46b93fa4c40e0ebfcc613a5fe0feaa65f
