### ISSUE TITLE
train_model_from_sigs Example?

### ISSUE THREAD

**Issue by NaturalFigurehead** [MTG/essentia#768]
Is there an example of the file structure that train_model_from_sigs (https://github.com/MTG/gaia/blob/master/src/bindings/pygaia/scripts/classification/train_model_from_sigs.py) requires?

I can't really tell  from the Essentia Faq.

**Comment by dbogdanov** [comment]
This script receives the input folder as an input parameter and it expects that folder to have subfolders corresponding to classes. Descriptor files with examples of each class should be located inside each subfolder.

**Comment by NaturalFigurehead** [comment]
Check out my sample project here https://github.com/NaturalFigurehead/trainerexample.

When I run `train_model_from_sigs.main('data', None)` I'm getting:

`running in dir data
['song2', 'song']
got 0 files in song2
got 0 files in song
Creating classification project /home/oliver/Documents/trainer/trainerexample/data/data.project
Traceback (most recent call last):
  File "tbtrainer.py", line 3, in <module>
    train_model_from_sigs.main('data', None)
  File "/usr/local/lib/python2.7/dist-packages/gaia2/scripts/classification/train_model_from_sigs.py", line 70, in main
    train_model.trainModel(groundtruth_name, yaml_name, project_file, project_dir, results_model_file)
  File "/usr/local/lib/python2.7/dist-packages/gaia2/scripts/classification/train_model.py", line 59, in trainModel
    groundtruth_file, filelist_file, project_file, datasets_dir, results_dir)
  File "/usr/local/lib/python2.7/dist-packages/gaia2/scripts/classification/generate_classification_project.py", line 41, in generateProject
    fl = yaml.load(open(filelist_file, 'r'))
IOError: [Errno 2] No such file or directory: '/home/oliver/Documents/trainer/trainerexample/data/filelist-yaml.yaml'`

The yaml descriptor files are generated from the standard music extractor.

**Comment by dbogdanov** [comment]
There may be some issue in the code around [here](https://github.com/MTG/gaia/blob/master/src/bindings/pygaia/scripts/classification/train_model_from_sigs.py#L62)

Possibly, in your case the ```filelist.yaml``` was generated, but the ```filelist-yaml.yaml``` was not. Are you using sig (yaml) descriptor files or json descriptor files?

**Comment by NaturalFigurehead** [comment]
I'm using sig. I updated my descriptor files to have the extension `sig` instead of `yaml` and now I'm getting this ouput: 

`running in dir data
['song2', 'song']
got 0 files in song2
got 0 files in song
converting sig
Failed to convert 0 files:
Creating classification project /home/oliver/Documents/trainer/trainerexample/data/data.project
Successfully written /home/oliver/Documents/trainer/trainerexample/data/data.project
INFO     ClassificationTaskManager  |  Merging original base dataset...
Harmonizing chunks so that they all have the same layout & history...
Traceback (most recent call last):
  File "tbtrainer.py", line 3, in <module>
    train_model_from_sigs.main('data', None)
  File "/usr/local/lib/python2.7/dist-packages/gaia2/scripts/classification/train_model_from_sigs.py", line 70, in main
    train_model.trainModel(groundtruth_name, yaml_name, project_file, project_dir, results_model_file)
  File "/usr/local/lib/python2.7/dist-packages/gaia2/scripts/classification/train_model.py", line 65, in trainModel
    run_tests.runTests(project_file)
  File "/usr/local/lib/python2.7/dist-packages/gaia2/scripts/classification/run_tests.py", line 55, in runTests
    test.run()
  File "/usr/local/lib/python2.7/dist-packages/gaia2/classification/classificationtaskmanager.py", line 177, in run
    self.mergeDataSet()
  File "/usr/local/lib/python2.7/dist-packages/gaia2/classification/classificationtaskmanager.py", line 170, in mergeDataSet
    mergeAll(self.conf['filelist'], self.conf['datasetFilename'], 5000, transfoFile = None)
  File "/usr/local/lib/python2.7/dist-packages/gaia2/fusion.py", line 160, in mergeAll
    vldescs, nandescs, rdescs = harmonizeChunks(partfiles)
  File "/usr/local/lib/python2.7/dist-packages/gaia2/fusion.py", line 86, in harmonizeChunks
    ds.load(partfiles[0])
IndexError: list index out of range`

It actually seems to complete and it creates the result files. It just doesn't recognize my descriptor files.

**Comment by dbogdanov** [comment]
@NaturalFigurehead To be able to train a classifier you need multiple (many!) training examples of each class. It appears that you only have one file of "song2" class and no files of "song" class. 

The training script loads all descriptor files and pre-processes descriptors before training. In particular, it removes descriptors that have a constant value across all training examples. In your case, you have only one training example (that is, one file) in your training data and therefore all descriptors are considered constant and removed.
