### ISSUE TITLE
Exception when training classifier models

### ISSUE THREAD

**Issue by NaturalFigurehead** [MTG/essentia#773]
I'm getting this exception when I try to train custom classifier models:

```
Traceback (most recent call last):
  File "tbtrainer.py", line 3, in <module>
    train_model.trainModel('test_groundtruth.yaml', 'test_filelist.yaml', 'test.prj', 'test', 'test.history')
  File "/usr/local/lib/python2.7/dist-packages/gaia2/scripts/classification/train_model.py", line 65, in trainModel
    run_tests.runTests(project_file)
  File "/usr/local/lib/python2.7/dist-packages/gaia2/scripts/classification/run_tests.py", line 55, in runTests
    test.run()
  File "/usr/local/lib/python2.7/dist-packages/gaia2/classification/classificationtaskmanager.py", line 178, in run
    self.applyPreprocessing()
  File "/usr/local/lib/python2.7/dist-packages/gaia2/classification/classificationtaskmanager.py", line 157, in applyPreprocessing
    ds = transform(ds, step['transfo'], step.get('params', {}))
  File "/usr/local/lib/python2.7/dist-packages/gaia2/__init__.py", line 6184, in transform
    return analyzer.analyze(dataset).applyToDataSet(dataset)
  File "/usr/local/lib/python2.7/dist-packages/gaia2/__init__.py", line 2945, in analyze
    return _gaia2.Analyzer_analyze(self, *args)
Exception: PointLayout: pattern "tonal.key_key" didn't match any descriptor

```
I'm running `train_model.py` like so:
```
from gaia2.scripts.classification import train_model

train_model.trainModel('test_groundtruth.yaml', 'test_filelist.yaml', 'test.prj', 'test', 'test.history')
```
I created the descriptor files with `essentia_streaming_extractor_music` using a profile to get yaml/sig descriptor files. 

The training script recognizes my 2 descriptor files and outputs `INFO     ClassificationTaskManager  |  Doing "nobands" preprocessing...` before encountering the exception.

**Comment by derekacosta** [comment]
Similar issue waiting for response

**Comment by NaturalFigurehead** [comment]
@derekacosta I'm not sure I understand. You're using that in your profile while running `essentia_streaming_extractor_music`? When I paste that into my profile I get a parser error. Can you share your entire profile file?

**Comment by dbogdanov** [comment]
```essentia_streaming_extractor_music``` has been updated and the key descriptor layout has changed. Now there are three different key estimations ```key_edm```, ```key_krumhansl``` and ```key_temperley```.  

We should update [classification_project_template.yaml](https://github.com/MTG/gaia/blob/master/src/bindings/pygaia/scripts/classification/classification_project_template.yaml) in Gaia accordingly (@pabloEntropia).
