### ISSUE TITLE
pip install essentia fails on arch linux python 3.7

### ISSUE THREAD

**Issue by kureta** [MTG/essentia#779]
I have attached the relevant part of the `pip install essentia` command. Please let me know if there is anything else I should do to pinpoint the cause of this error.

```
   /usr/bin/cmake -P cmake_install.cmake
    -- Install configuration: "Release"
    -- Installing: /tmp/pip-install-6li_uhzc/essentia/packaging/debian_3rdparty/lib/pkgconfig/libchromaprint.pc
    -- Installing: /tmp/pip-install-6li_uhzc/essentia/packaging/debian_3rdparty/lib/libchromaprint.a
    -- Installing: /tmp/pip-install-6li_uhzc/essentia/packaging/debian_3rdparty/include/chromaprint.h
    Traceback (most recent call last):
      File "/tmp/pip-install-6li_uhzc/essentia/.waf3-1.9.11-af9ceda667eab9a2b3fb893b34583f23/waflib/Node.py", line 295, in ant_iter
        raise StopIteration
    StopIteration
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "/tmp/pip-install-6li_uhzc/essentia/.waf3-1.9.11-af9ceda667eab9a2b3fb893b34583f23/waflib/Scripting.py", line 122, in waf_entry_point
        run_commands()
      File "/tmp/pip-install-6li_uhzc/essentia/.waf3-1.9.11-af9ceda667eab9a2b3fb893b34583f23/waflib/Scripting.py", line 179, in run_commands
        parse_options()
      File "/tmp/pip-install-6li_uhzc/essentia/.waf3-1.9.11-af9ceda667eab9a2b3fb893b34583f23/waflib/Scripting.py", line 152, in parse_options
        Context.create_context('options').execute()
      File "/tmp/pip-install-6li_uhzc/essentia/.waf3-1.9.11-af9ceda667eab9a2b3fb893b34583f23/waflib/Options.py", line 149, in execute
        super(OptionsContext,self).execute()
      File "/tmp/pip-install-6li_uhzc/essentia/.waf3-1.9.11-af9ceda667eab9a2b3fb893b34583f23/waflib/Context.py", line 88, in execute
        self.recurse([os.path.dirname(g_module.root_path)])
      File "/tmp/pip-install-6li_uhzc/essentia/.waf3-1.9.11-af9ceda667eab9a2b3fb893b34583f23/waflib/Context.py", line 129, in recurse
        user_function(self)
      File "/tmp/pip-install-6li_uhzc/essentia/wscript", line 35, in options
        ctx.load('compiler_cxx compiler_c python')
      File "/tmp/pip-install-6li_uhzc/essentia/.waf3-1.9.11-af9ceda667eab9a2b3fb893b34583f23/waflib/Context.py", line 85, in load
        fun(self)
      File "/tmp/pip-install-6li_uhzc/essentia/.waf3-1.9.11-af9ceda667eab9a2b3fb893b34583f23/waflib/Tools/compiler_cxx.py", line 40, in options
        opt.load_special_tools('cxx_*.py')
      File "/tmp/pip-install-6li_uhzc/essentia/.waf3-1.9.11-af9ceda667eab9a2b3fb893b34583f23/waflib/Context.py", line 319, in load_special_tools
        lst=self.root.find_node(waf_dir).find_node('waflib/extras').ant_glob(var)
      File "/tmp/pip-install-6li_uhzc/essentia/.waf3-1.9.11-af9ceda667eab9a2b3fb893b34583f23/waflib/Node.py", line 344, in ant_glob
        ret=[x for x in self.ant_iter(accept=accept,pats=[to_pat(incl),to_pat(excl)],maxdepth=kw.get('maxdepth',25),dir=dir,src=src,remove=kw.get('remove',True))]
      File "/tmp/pip-install-6li_uhzc/essentia/.waf3-1.9.11-af9ceda667eab9a2b3fb893b34583f23/waflib/Node.py", line 344, in <listcomp>
        ret=[x for x in self.ant_iter(accept=accept,pats=[to_pat(incl),to_pat(excl)],maxdepth=kw.get('maxdepth',25),dir=dir,src=src,remove=kw.get('remove',True))]
    RuntimeError: generator raised StopIteration
    Traceback (most recent call last):
      File "/tmp/pip-install-6li_uhzc/essentia/.waf3-1.9.11-af9ceda667eab9a2b3fb893b34583f23/waflib/Node.py", line 295, in ant_iter
        raise StopIteration
    StopIteration
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "/tmp/pip-install-6li_uhzc/essentia/.waf3-1.9.11-af9ceda667eab9a2b3fb893b34583f23/waflib/Scripting.py", line 122, in waf_entry_point
        run_commands()
      File "/tmp/pip-install-6li_uhzc/essentia/.waf3-1.9.11-af9ceda667eab9a2b3fb893b34583f23/waflib/Scripting.py", line 179, in run_commands
        parse_options()
      File "/tmp/pip-install-6li_uhzc/essentia/.waf3-1.9.11-af9ceda667eab9a2b3fb893b34583f23/waflib/Scripting.py", line 152, in parse_options
        Context.create_context('options').execute()
      File "/tmp/pip-install-6li_uhzc/essentia/.waf3-1.9.11-af9ceda667eab9a2b3fb893b34583f23/waflib/Options.py", line 149, in execute
        super(OptionsContext,self).execute()
      File "/tmp/pip-install-6li_uhzc/essentia/.waf3-1.9.11-af9ceda667eab9a2b3fb893b34583f23/waflib/Context.py", line 88, in execute
        self.recurse([os.path.dirname(g_module.root_path)])
      File "/tmp/pip-install-6li_uhzc/essentia/.waf3-1.9.11-af9ceda667eab9a2b3fb893b34583f23/waflib/Context.py", line 129, in recurse
        user_function(self)
      File "/tmp/pip-install-6li_uhzc/essentia/wscript", line 35, in options
        ctx.load('compiler_cxx compiler_c python')
      File "/tmp/pip-install-6li_uhzc/essentia/.waf3-1.9.11-af9ceda667eab9a2b3fb893b34583f23/waflib/Context.py", line 85, in load
        fun(self)
      File "/tmp/pip-install-6li_uhzc/essentia/.waf3-1.9.11-af9ceda667eab9a2b3fb893b34583f23/waflib/Tools/compiler_cxx.py", line 40, in options
        opt.load_special_tools('cxx_*.py')
      File "/tmp/pip-install-6li_uhzc/essentia/.waf3-1.9.11-af9ceda667eab9a2b3fb893b34583f23/waflib/Context.py", line 319, in load_special_tools
        lst=self.root.find_node(waf_dir).find_node('waflib/extras').ant_glob(var)
      File "/tmp/pip-install-6li_uhzc/essentia/.waf3-1.9.11-af9ceda667eab9a2b3fb893b34583f23/waflib/Node.py", line 344, in ant_glob
        ret=[x for x in self.ant_iter(accept=accept,pats=[to_pat(incl),to_pat(excl)],maxdepth=kw.get('maxdepth',25),dir=dir,src=src,remove=kw.get('remove',True))]
      File "/tmp/pip-install-6li_uhzc/essentia/.waf3-1.9.11-af9ceda667eab9a2b3fb893b34583f23/waflib/Node.py", line 344, in <listcomp>
        ret=[x for x in self.ant_iter(accept=accept,pats=[to_pat(incl),to_pat(excl)],maxdepth=kw.get('maxdepth',25),dir=dir,src=src,remove=kw.get('remove',True))]
    RuntimeError: generator raised StopIteration
    Traceback (most recent call last):
      File "/tmp/pip-install-6li_uhzc/essentia/.waf3-1.9.11-af9ceda667eab9a2b3fb893b34583f23/waflib/Node.py", line 295, in ant_iter
        raise StopIteration
    StopIteration
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "/tmp/pip-install-6li_uhzc/essentia/.waf3-1.9.11-af9ceda667eab9a2b3fb893b34583f23/waflib/Scripting.py", line 122, in waf_entry_point
        run_commands()
      File "/tmp/pip-install-6li_uhzc/essentia/.waf3-1.9.11-af9ceda667eab9a2b3fb893b34583f23/waflib/Scripting.py", line 179, in run_commands
        parse_options()
      File "/tmp/pip-install-6li_uhzc/essentia/.waf3-1.9.11-af9ceda667eab9a2b3fb893b34583f23/waflib/Scripting.py", line 152, in parse_options
        Context.create_context('options').execute()
      File "/tmp/pip-install-6li_uhzc/essentia/.waf3-1.9.11-af9ceda667eab9a2b3fb893b34583f23/waflib/Options.py", line 149, in execute
        super(OptionsContext,self).execute()
      File "/tmp/pip-install-6li_uhzc/essentia/.waf3-1.9.11-af9ceda667eab9a2b3fb893b34583f23/waflib/Context.py", line 88, in execute
        self.recurse([os.path.dirname(g_module.root_path)])
      File "/tmp/pip-install-6li_uhzc/essentia/.waf3-1.9.11-af9ceda667eab9a2b3fb893b34583f23/waflib/Context.py", line 129, in recurse
        user_function(self)
      File "/tmp/pip-install-6li_uhzc/essentia/wscript", line 35, in options
        ctx.load('compiler_cxx compiler_c python')
      File "/tmp/pip-install-6li_uhzc/essentia/.waf3-1.9.11-af9ceda667eab9a2b3fb893b34583f23/waflib/Context.py", line 85, in load
        fun(self)
      File "/tmp/pip-install-6li_uhzc/essentia/.waf3-1.9.11-af9ceda667eab9a2b3fb893b34583f23/waflib/Tools/compiler_cxx.py", line 40, in options
        opt.load_special_tools('cxx_*.py')
      File "/tmp/pip-install-6li_uhzc/essentia/.waf3-1.9.11-af9ceda667eab9a2b3fb893b34583f23/waflib/Context.py", line 319, in load_special_tools
        lst=self.root.find_node(waf_dir).find_node('waflib/extras').ant_glob(var)
      File "/tmp/pip-install-6li_uhzc/essentia/.waf3-1.9.11-af9ceda667eab9a2b3fb893b34583f23/waflib/Node.py", line 344, in ant_glob
        ret=[x for x in self.ant_iter(accept=accept,pats=[to_pat(incl),to_pat(excl)],maxdepth=kw.get('maxdepth',25),dir=dir,src=src,remove=kw.get('remove',True))]
      File "/tmp/pip-install-6li_uhzc/essentia/.waf3-1.9.11-af9ceda667eab9a2b3fb893b34583f23/waflib/Node.py", line 344, in <listcomp>
        ret=[x for x in self.ant_iter(accept=accept,pats=[to_pat(incl),to_pat(excl)],maxdepth=kw.get('maxdepth',25),dir=dir,src=src,remove=kw.get('remove',True))]
    RuntimeError: generator raised StopIteration
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-6li_uhzc/essentia/setup.py", line 116, in <module>
        'install_lib': EssentiaInstall
      File "/home/kureta/.pyenv/versions/3.7.0/envs/zak-pytorch/lib/python3.7/site-packages/setuptools/__init__.py", line 131, in setup
        return distutils.core.setup(**attrs)
      File "/home/kureta/.pyenv/versions/3.7.0/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/kureta/.pyenv/versions/3.7.0/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/home/kureta/.pyenv/versions/3.7.0/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/kureta/.pyenv/versions/3.7.0/envs/zak-pytorch/lib/python3.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/home/kureta/.pyenv/versions/3.7.0/lib/python3.7/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/home/kureta/.pyenv/versions/3.7.0/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/kureta/.pyenv/versions/3.7.0/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/kureta/.pyenv/versions/3.7.0/lib/python3.7/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/home/kureta/.pyenv/versions/3.7.0/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/kureta/.pyenv/versions/3.7.0/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-6li_uhzc/essentia/setup.py", line 46, in run
        library = glob.glob('tmp/lib/python*/*-packages/essentia')[0]
    IndexError: list index out of range
    
    ----------------------------------------
Command "/home/kureta/.pyenv/versions/3.7.0/envs/zak-pytorch/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-6li_uhzc/essentia/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-9d_obpka/install-record.txt --single-version-externally-managed --compile --install-headers /home/kureta/.pyenv/versions/3.7.0/envs/zak-pytorch/include/site/python3.7/essentia" failed with error code 1 in /tmp/pip-install-6li_uhzc/essentia/

```

**Comment by dbogdanov** [comment]
As Python 3.7 just came out, we haven't provided the wheels for it yet. We'll update on PyPI with new manylinux wheels soon.

**Comment by Rybak5611** [comment]
Same error with python 3.6

**Comment by thefreakingmind12** [comment]
This is not working with python3.6 also.

**Comment by iluvcapra** [comment]
I may have the same issue, on macOS Mojave. This failed on pip3 (Python 3.7) and pip2.7

`[many lines...]
      File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/private/var/folders/vt/54xxhct17xj0d26f03y0_28m0000gn/T/pip-install-8ezWBn/essentia/setup.py", line 46, in run
        library = glob.glob('tmp/lib/python*/*-packages/essentia')[0]
    IndexError: list index out of range
   
[error.txt](https://github.com/MTG/essentia/files/2587944/error.txt)
`
