### ISSUE TITLE
Building for Python 3.7 on OS X 10.13.6 - compiler error

### ISSUE THREAD

**Issue by franPul** [MTG/essentia#781]
I've been trying to build essentia on OS X 10.13.6 to be used with python 3.7.
For that purpose, I've configured waf with this line

./waf configure --build-static --with-python --python=/usr/local/bin/python3 --with-cpptests

And when building it, I get the following errors,
[350/365] Compiling src/python/pytypes/pypool.cpp
In file included from ../src/python/essentia.cpp:43:
../src/python/pystreamingalgorithm.cpp:169:9: error: cannot initialize a
variable of type 'char *' with an rvalue of type 'const char *'
  char* name = PyString_AsString(obj);
        ^      ~~~~~~~~~~~~~~~~~~~~~~
../src/python/pystreamingalgorithm.cpp:180:9: error: cannot initialize a
variable of type 'char *' with an rvalue of type 'const char *'
  char* name = PyString_AsString(obj);
        ^      ~~~~~~~~~~~~~~~~~~~~~~
../src/python/pystreamingalgorithm.cpp:253:9: error: cannot initialize a
variable of type 'char *' with an rvalue of type 'const char *'
  char* name = PyString_AsString(obj);
        ^      ~~~~~~~~~~~~~~~~~~~~~~
../src/python/pystreamingalgorithm.cpp:273:9: error: cannot initialize a
variable of type 'char *' with an rvalue of type 'const char *'
  char* name = PyString_AsString(obj);
        ^      ~~~~~~~~~~~~~~~~~~~~~~
4 errors generated.

Any idea how I could fix this?

**Comment by sildeag** [comment]
Have you tried: `python3 ./waf configure --build-static --with-python --with-cpptests`

**Comment by franPul** [comment]
trying python3 was my first attempt, and I got this error msg,

Traceback (most recent call last):
  File "/Users/Hydroloop/Documents/Freelance/Noiiz/Development/essentia/.waf3-1.9.11-af9ceda667eab9a2b3fb893b34583f23/waflib/Node.py", line 295, in ant_iter
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/Hydroloop/Documents/Freelance/Noiiz/Development/essentia/.waf3-1.9.11-af9ceda667eab9a2b3fb893b34583f23/waflib/Scripting.py", line 122, in waf_entry_point
    run_commands()
  File "/Users/Hydroloop/Documents/Freelance/Noiiz/Development/essentia/.waf3-1.9.11-af9ceda667eab9a2b3fb893b34583f23/waflib/Scripting.py", line 179, in run_commands
    parse_options()
  File "/Users/Hydroloop/Documents/Freelance/Noiiz/Development/essentia/.waf3-1.9.11-af9ceda667eab9a2b3fb893b34583f23/waflib/Scripting.py", line 152, in parse_options
    Context.create_context('options').execute()
  File "/Users/Hydroloop/Documents/Freelance/Noiiz/Development/essentia/.waf3-1.9.11-af9ceda667eab9a2b3fb893b34583f23/waflib/Options.py", line 149, in execute
    super(OptionsContext,self).execute()
  File "/Users/Hydroloop/Documents/Freelance/Noiiz/Development/essentia/.waf3-1.9.11-af9ceda667eab9a2b3fb893b34583f23/waflib/Context.py", line 88, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "/Users/Hydroloop/Documents/Freelance/Noiiz/Development/essentia/.waf3-1.9.11-af9ceda667eab9a2b3fb893b34583f23/waflib/Context.py", line 129, in recurse
    user_function(self)
  File "/Users/Hydroloop/Documents/Freelance/Noiiz/Development/essentia/wscript", line 35, in options
    ctx.load('compiler_cxx compiler_c python')
  File "/Users/Hydroloop/Documents/Freelance/Noiiz/Development/essentia/.waf3-1.9.11-af9ceda667eab9a2b3fb893b34583f23/waflib/Context.py", line 85, in load
    fun(self)
  File "/Users/Hydroloop/Documents/Freelance/Noiiz/Development/essentia/.waf3-1.9.11-af9ceda667eab9a2b3fb893b34583f23/waflib/Tools/compiler_cxx.py", line 40, in options
    opt.load_special_tools('cxx_*.py')
  File "/Users/Hydroloop/Documents/Freelance/Noiiz/Development/essentia/.waf3-1.9.11-af9ceda667eab9a2b3fb893b34583f23/waflib/Context.py", line 319, in load_special_tools
    lst=self.root.find_node(waf_dir).find_node('waflib/extras').ant_glob(var)
  File "/Users/Hydroloop/Documents/Freelance/Noiiz/Development/essentia/.waf3-1.9.11-af9ceda667eab9a2b3fb893b34583f23/waflib/Node.py", line 344, in ant_glob
    ret=[x for x in self.ant_iter(accept=accept,pats=[to_pat(incl),to_pat(excl)],maxdepth=kw.get('maxdepth',25),dir=dir,src=src,remove=kw.get('remove',True))]
  File "/Users/Hydroloop/Documents/Freelance/Noiiz/Development/essentia/.waf3-1.9.11-af9ceda667eab9a2b3fb893b34583f23/waflib/Node.py", line 344, in <listcomp>
    ret=[x for x in self.ant_iter(accept=accept,pats=[to_pat(incl),to_pat(excl)],maxdepth=kw.get('maxdepth',25),dir=dir,src=src,remove=kw.get('remove',True))]
RuntimeError: generator raised StopIteration

**Comment by franPul** [comment]
I can try to fix the cpp files, and see if it works like that.

**Comment by sildeag** [comment]
Seems like worth trying.  However, when you generated `waf` you needed to use python3 or python2 appropriate to your needs.  Back in `essentia` folder created by your `github` clone, backup the `waf` file and replace it with the one you've generated in your `waf` folder.  I would stick with python2 as it would have been more widely used.

Problem is I don't think python 3.7 is supported, hopefully someone else will chime in about that.
My pull request was only tested on python 2.7 and 3.6 on Ubuntu OS not OS X.  `pyext_PATTERN` is a problem I've addressed but it may not affect Macs.

**Comment by franPul** [comment]
managed to install it, after replacing those lines with const char*. Now i am getting some issues when importing it tho :(

**Comment by alastair** [comment]
We have an open patch for compiling against python 3.7: https://github.com/MTG/essentia/pull/774, we've had no problems running it with these changes.

**Comment by franPul** [comment]
yes, did the same fix and it works fine. Thank you.
