### ISSUE TITLE
pip install essentia fails on windows 10

### ISSUE THREAD

**Issue by bhui** [MTG/essentia#859]
where can I find the lost dependcy? 
For example, I down load ffmpeg lib from https://ffmpeg.zeranoe.com/builds/  and add to path, but still the same error.
and pip install yaml-0.1/fftw3f etc. return ERROR: Could not find a version that satisfies the requirement yaml-0.1

```
(python35) λ python --version
Python 3.5.5 :: Anaconda, Inc.

(python35) λ pip install essentia
Collecting essentia
  Using cached https://files.pythonhosted.org/packages/40/5d/76217a30fa41f3258d41d275acca9339f77b88356b6da6dbedcfab7c3712/essentia-2.1b5.dev532.tar.gz
Requirement already satisfied: numpy>=1.8.2 in c:\users\xman\appdata\local\conda\conda\envs\python35\lib\site-packages (from essentia) (1.15.0)
Requirement already satisfied: six in c:\users\xman\appdata\local\conda\conda\envs\python35\lib\site-packages (from essentia) (1.11.0)
Requirement already satisfied: pyyaml in c:\users\xman\appdata\local\conda\conda\envs\python35\lib\site-packages (from essentia) (3.13)
Building wheels for collected packages: essentia
  Building wheel for essentia (setup.py) ... error
  ERROR: Complete output from command 'c:\users\xman\appdata\local\conda\conda\envs\python35\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\xman\\AppData\\Local\\Temp\\pip-install-ggegmw5k\\essentia\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\xman\AppData\Local\Temp\pip-wheel-2cud3mk3' --python-tag cp35:
  ERROR: Error parsing the number of dev commits: %s
  c:\users\xman\appdata\local\conda\conda\envs\python35\lib\site-packages\setuptools\dist.py:475: UserWarning: Normalizing '2.1-beta5-dev0' to '2.1b5.dev0'
    normalized_version,
  running bdist_wheel
  running build
  running build_ext
  '.' 不是内部或外部命令，也不是可运行的程序
  或批处理文件。
  Setting top to                           : C:\Users\xman\AppData\Local\Temp\pip-install-ggegmw5k\essentia
  Setting out to                           : C:\Users\xman\AppData\Local\Temp\pip-install-ggegmw5k\essentia\build
  → configuring the project in C:\Users\xman\AppData\Local\Temp\pip-install-ggegmw5k\essentia
  → Building in release mode
  Building on win32
  Checking for 'msvc' (C++ compiler)       : C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.20.27508\bin\HostX64\x64\CL.exe
  Checking for 'msvc' (C compiler)         : C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.20.27508\bin\HostX64\x64\CL.exe
  Checking for program 'pkg-config'        : C:\cygwin64\bin\pkg-config.exe
  Checking for 'libavcodec' >= 55.34.1     : not found
  Checking for 'libavformat'               : not found
  Checking for 'libavutil'                 : not found
  Checking for 'libavresample'             : not found
  Checking for 'samplerate'                : not found
  Checking for 'taglib' >= 1.9             : not found
  Checking for 'yaml-0.1'                  : not found
  Checking for 'fftw3f'                    : not found
  Checking for 'libchromaprint'            : not found
  Checking for 'msvc' (C compiler)         : C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.20.27508\bin\HostX64\x64\CL.exe
  Checking for program 'python'            : c:\users\xman\appdata\local\conda\conda\envs\python35\python.exe

  Checking for python version >= 2.7.0     : 3.5.5
  → Configuring for python3
  python-config                            : not found
  Checking for library python3.5 in $prefix/libs : not found
  Checking for library python3.5m in $prefix/libs : not found
  Checking for library python35 in $prefix/libs   : yes
  Traceback (most recent call last):
    File "C:\Users\xman\AppData\Local\Temp\pip-install-ggegmw5k\essentia\waf3-2.0.10-cf8ca5fa84387374f6d66295baab59ec\waflib\Scripting.py", line 119, in waf_entry_point
      run_commands()
    File "C:\Users\xman\AppData\Local\Temp\pip-install-ggegmw5k\essentia\waf3-2.0.10-cf8ca5fa84387374f6d66295baab59ec\waflib\Scripting.py", line 179, in run_commands
      ctx=run_command(cmd_name)
    File "C:\Users\xman\AppData\Local\Temp\pip-install-ggegmw5k\essentia\waf3-2.0.10-cf8ca5fa84387374f6d66295baab59ec\waflib\Scripting.py", line 170, in run_command
      ctx.execute()
    File "C:\Users\xman\AppData\Local\Temp\pip-install-ggegmw5k\essentia\waf3-2.0.10-cf8ca5fa84387374f6d66295baab59ec\waflib\Configure.py", line 85, in execute
      super(ConfigurationContext,self).execute()
    File "C:\Users\xman\AppData\Local\Temp\pip-install-ggegmw5k\essentia\waf3-2.0.10-cf8ca5fa84387374f6d66295baab59ec\waflib\Context.py", line 85, in execute
      self.recurse([os.path.dirname(g_module.root_path)])
    File "C:\Users\xman\AppData\Local\Temp\pip-install-ggegmw5k\essentia\waf3-2.0.10-cf8ca5fa84387374f6d66295baab59ec\waflib\Context.py", line 126, in recurse
      user_function(self)
    File "C:\Users\xman\AppData\Local\Temp\pip-install-ggegmw5k\essentia\wscript", line 300, in configure
      ctx.recurse('src')
    File "C:\Users\xman\AppData\Local\Temp\pip-install-ggegmw5k\essentia\waf3-2.0.10-cf8ca5fa84387374f6d66295baab59ec\waflib\Context.py", line 126, in recurse
      user_function(self)
    File "C:\Users\xman\AppData\Local\Temp\pip-install-ggegmw5k\essentia\src\wscript", line 176, in configure

      ctx.recurse('python')
    File "C:\Users\xman\AppData\Local\Temp\pip-install-ggegmw5k\essentia\waf3-2.0.10-cf8ca5fa84387374f6d66295baab59ec\waflib\Context.py", line 126, in recurse
      user_function(self)
    File "C:\Users\xman\AppData\Local\Temp\pip-install-ggegmw5k\essentia\src\python\wscript", line 22, in configure
      ctx.check_python_headers(features='pyext')
    File "C:\Users\xman\AppData\Local\Temp\pip-install-ggegmw5k\essentia\waf3-2.0.10-cf8ca5fa84387374f6d66295baab59ec\waflib\Configure.py", line 174, in fun
      return f(*k,**kw)
    File "C:\Users\xman\AppData\Local\Temp\pip-install-ggegmw5k\essentia\waf3-2.0.10-cf8ca5fa84387374f6d66295baab59ec\waflib\Tools\python.py", line 288, in check_python_headers
      dist_compiler.initialize()
    File "c:\users\xman\appdata\local\conda\conda\envs\python35\lib\distutils\msvc9compiler.py", line 374, in initialize
      vc_env = query_vcvarsall(VERSION, plat_spec)
    File "c:\users\xman\appdata\local\conda\conda\envs\python35\lib\distutils\msvc9compiler.py", line 262, in query_vcvarsall
      raise DistutilsPlatformError("Unable to find vcvarsall.bat")
  distutils.errors.DistutilsPlatformError: Unable to find vcvarsall.bat
  The project was not configured: run "waf configure" first!
  The project was not configured: run "waf configure" first!
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\xman\AppData\Local\Temp\pip-install-ggegmw5k\essentia\setup.py", line 116, in <module>
      'install_lib': EssentiaInstall
    File "c:\users\xman\appdata\local\conda\conda\envs\python35\lib\site-packages\setuptools\__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "c:\users\xman\appdata\local\conda\conda\envs\python35\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "c:\users\xman\appdata\local\conda\conda\envs\python35\lib\distutils\dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "c:\users\xman\appdata\local\conda\conda\envs\python35\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "c:\users\xman\appdata\local\conda\conda\envs\python35\lib\site-packages\wheel\bdist_wheel.py", line 202, in run
      self.run_command('build')
    File "c:\users\xman\appdata\local\conda\conda\envs\python35\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\users\xman\appdata\local\conda\conda\envs\python35\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "c:\users\xman\appdata\local\conda\conda\envs\python35\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "c:\users\xman\appdata\local\conda\conda\envs\python35\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\users\xman\appdata\local\conda\conda\envs\python35\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "C:\Users\xman\AppData\Local\Temp\pip-install-ggegmw5k\essentia\setup.py", line 46, in run
      library = glob.glob('tmp/lib/python*/*-packages/essentia')[0]
  IndexError: list index out of range
  ----------------------------------------
  ERROR: Failed building wheel for essentia
  Running setup.py clean for essentia
Failed to build essentia
Installing collected packages: essentia
  Running setup.py install for essentia ... error
    ERROR: Complete output from command 'c:\users\xman\appdata\local\conda\conda\envs\python35\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\xman\\AppData\\Local\\Temp\\pip-install-ggegmw5k\\essentia\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\xman\AppData\Local\Temp\pip-record-lo2mgkrc\install-record.txt' --single-version-externally-managed --compile:
    ERROR: Error parsing the number of dev commits: %s
    c:\users\xman\appdata\local\conda\conda\envs\python35\lib\site-packages\setuptools\dist.py:475: UserWarning: Normalizing '2.1-beta5-dev0' to '2.1b5.dev0'
      normalized_version,
    running install
    running build
    running build_ext
    '.' 不是内部或外部命令，也不是可运行的程序
    或批处理文件。
    Setting top to                           : C:\Users\xman\AppData\Local\Temp\pip-install-ggegmw5k\essentia

    Setting out to                           : C:\Users\xman\AppData\Local\Temp\pip-install-ggegmw5k\essentia\build
    → configuring the project in C:\Users\xman\AppData\Local\Temp\pip-install-ggegmw5k\essentia
    → Building in release mode
    Building on win32
    Checking for 'msvc' (C++ compiler)       : C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.20.27508\bin\HostX64\x64\CL.exe
    Checking for 'msvc' (C compiler)         : C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.20.27508\bin\HostX64\x64\CL.exe
    Checking for program 'pkg-config'        : C:\cygwin64\bin\pkg-config.exe
    Checking for 'libavcodec' >= 55.34.1     : not found
    Checking for 'libavformat'               : not found
    Checking for 'libavutil'                 : not found
    Checking for 'libavresample'             : not found
    Checking for 'samplerate'                : not found
    Checking for 'taglib' >= 1.9             : not found
    Checking for 'yaml-0.1'                  : not found
    Checking for 'fftw3f'                    : not found
    Checking for 'libchromaprint'            : not found
    Checking for 'msvc' (C compiler)         : C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.20.27508\bin\HostX64\x64\CL.exe
    Checking for program 'python'            : c:\users\xman\appdata\local\conda\conda\envs\python35\python.exe
    Checking for python version >= 2.7.0     : 3.5.5
    → Configuring for python3
    python-config                            : not found
    Checking for library python3.5 in $prefix/libs : not found
    Checking for library python3.5m in $prefix/libs : not found
    Checking for library python35 in $prefix/libs   : yes
    Traceback (most recent call last):
      File "C:\Users\xman\AppData\Local\Temp\pip-install-ggegmw5k\essentia\waf3-2.0.10-cf8ca5fa84387374f6d66295baab59ec\waflib\Scripting.py", line 119, in waf_entry_point
        run_commands()
      File "C:\Users\xman\AppData\Local\Temp\pip-install-ggegmw5k\essentia\waf3-2.0.10-cf8ca5fa84387374f6d66295baab59ec\waflib\Scripting.py", line 179, in run_commands
        ctx=run_command(cmd_name)
      File "C:\Users\xman\AppData\Local\Temp\pip-install-ggegmw5k\essentia\waf3-2.0.10-cf8ca5fa84387374f6d66295baab59ec\waflib\Scripting.py", line 170, in run_command
        ctx.execute()
      File "C:\Users\xman\AppData\Local\Temp\pip-install-ggegmw5k\essentia\waf3-2.0.10-cf8ca5fa84387374f6d66295baab59ec\waflib\Configure.py", line 85, in execute
        super(ConfigurationContext,self).execute()
      File "C:\Users\xman\AppData\Local\Temp\pip-install-ggegmw5k\essentia\waf3-2.0.10-cf8ca5fa84387374f6d66295baab59ec\waflib\Context.py", line 85, in execute
        self.recurse([os.path.dirname(g_module.root_path)])
      File "C:\Users\xman\AppData\Local\Temp\pip-install-ggegmw5k\essentia\waf3-2.0.10-cf8ca5fa84387374f6d66295baab59ec\waflib\Context.py", line 126, in recurse
        user_function(self)
      File "C:\Users\xman\AppData\Local\Temp\pip-install-ggegmw5k\essentia\wscript", line 300, in configure
        ctx.recurse('src')
      File "C:\Users\xman\AppData\Local\Temp\pip-install-ggegmw5k\essentia\waf3-2.0.10-cf8ca5fa84387374f6d66295baab59ec\waflib\Context.py", line 126, in recurse
        user_function(self)
      File "C:\Users\xman\AppData\Local\Temp\pip-install-ggegmw5k\essentia\src\wscript", line 176, in configure
        ctx.recurse('python')
      File "C:\Users\xman\AppData\Local\Temp\pip-install-ggegmw5k\essentia\waf3-2.0.10-cf8ca5fa84387374f6d66295baab59ec\waflib\Context.py", line 126, in recurse
        user_function(self)
      File "C:\Users\xman\AppData\Local\Temp\pip-install-ggegmw5k\essentia\src\python\wscript", line 22, in configure
        ctx.check_python_headers(features='pyext')
      File "C:\Users\xman\AppData\Local\Temp\pip-install-ggegmw5k\essentia\waf3-2.0.10-cf8ca5fa84387374f6d66295baab59ec\waflib\Configure.py", line 174, in fun
        return f(*k,**kw)
      File "C:\Users\xman\AppData\Local\Temp\pip-install-ggegmw5k\essentia\waf3-2.0.10-cf8ca5fa84387374f6d66295baab59ec\waflib\Tools\python.py", line 288, in check_python_headers
        dist_compiler.initialize()
      File "c:\users\xman\appdata\local\conda\conda\envs\python35\lib\distutils\msvc9compiler.py", line 374, in initialize
        vc_env = query_vcvarsall(VERSION, plat_spec)
      File "c:\users\xman\appdata\local\conda\conda\envs\python35\lib\distutils\msvc9compiler.py", line 262, in query_vcvarsall
        raise DistutilsPlatformError("Unable to find vcvarsall.bat")
    distutils.errors.DistutilsPlatformError: Unable to find vcvarsall.bat
    The project was not configured: run "waf configure" first!
    The project was not configured: run "waf configure" first!
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\xman\AppData\Local\Temp\pip-install-ggegmw5k\essentia\setup.py", line 116, in <module>
        'install_lib': EssentiaInstall
      File "c:\users\xman\appdata\local\conda\conda\envs\python35\lib\site-packages\setuptools\__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "c:\users\xman\appdata\local\conda\conda\envs\python35\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\xman\appdata\local\conda\conda\envs\python35\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "c:\users\xman\appdata\local\conda\conda\envs\python35\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\users\xman\appdata\local\conda\conda\envs\python35\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\users\xman\appdata\local\conda\conda\envs\python35\lib\distutils\command\install.py", line 539, in run
        self.run_command('build')
      File "c:\users\xman\appdata\local\conda\conda\envs\python35\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\xman\appdata\local\conda\conda\envs\python35\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\users\xman\appdata\local\conda\conda\envs\python35\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "c:\users\xman\appdata\local\conda\conda\envs\python35\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\xman\appdata\local\conda\conda\envs\python35\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\xman\AppData\Local\Temp\pip-install-ggegmw5k\essentia\setup.py", line 46, in run
        library = glob.glob('tmp/lib/python*/*-packages/essentia')[0]
    IndexError: list index out of range
    ----------------------------------------
ERROR: Command "'c:\users\xman\appdata\local\conda\conda\envs\python35\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\xman\\AppData\\Local\\Temp\\pip-install-ggegmw5k\\essentia\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\xman\AppData\Local\Temp\pip-record-lo2mgkrc\install-record.txt' --single-version-externally-managed --compile" failed with error code 1 in C:\Users\xman\AppData\Local\Temp\pip-install-ggegmw5k\essentia\


```

**Comment by dbogdanov** [comment]
This is not implemented yet natively. You can use `pip install essentia` inside [Bash On Ubuntu](https://essentia.upf.edu/documentation/installing.html#building-essentia-on-windows-10-via-bash-on-ubuntu).
