### ISSUE TITLE
Error on python3 ./waf install

### ISSUE THREAD

**Issue by khachatur-kena** [MTG/essentia#930]
I'm running Ubuntu for Windows. Everything was fine until it complied essentia.pc.in

`Build failed
Traceback (most recent call last):
  File "/mnt/c/Users/Khachatur/essentia/.waf3-2.0.10-cf8ca5fa84387374f6d66295baab59ec/waflib/Task.py", line 172, in process
    ret=self.run()
  File "/mnt/c/Users/Khachatur/essentia/.waf3-2.0.10-cf8ca5fa84387374f6d66295baab59ec/waflib/Build.py", line 540, in run
    x.parent.mkdir()
  File "/mnt/c/Users/Khachatur/essentia/.waf3-2.0.10-cf8ca5fa84387374f6d66295baab59ec/waflib/Node.py", line 188, in mkdir
    raise Errors.WafError('Could not create the directory %r'%self)
waflib.Errors.WafError: Could not create the directory /usr/local/lib/pkgconfig`

**Comment by alastair** [comment]
Does this error occur when you are running `./waf`, or `./waf install`?
Are you using the linux subsystem for windows?

**Comment by palonso** [comment]
After reproducing this issue we have found that it is due to lack of permission.

Run `sudo python3 waf install` to fix it.
